package com.tangenta.repositories.impl;

import com.tangenta.data.pojo.QuestionType;
import com.tangenta.data.pojo.mybatis.MQuestion;
import com.tangenta.data.pojo.QuestionClassification;
import com.tangenta.repositories.QuestionRepository;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Repository;

import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

@Repository
@Profile("dev-test")
public class TestQuestionRepository implements QuestionRepository {

    @Override
    public List<MQuestion> getAllQuestions() {
        return allQuestions;
    }

    @Override
    public List<MQuestion> getQuestionsByClassAndType(List<QuestionClassification> classifications, List<QuestionType> types) {
        return allQuestions.stream()
                .filter(q -> classifications.contains(q.getClassification()) && types.contains(q.getType()))
                .collect(Collectors.toList());
    }

    @Override
    public MQuestion findQuestionById(Long questionId) {
        for (MQuestion q: allQuestions) {
            if (q.getQuestionId().equals(questionId)) return q;
        }
        return null;
    }

    @Override
    public void createQuestion(MQuestion q) {
        allQuestions.add(new MQuestion(q.getQuestionId(), q.getDescription(), q.getType(),
                q.getClassification(), q.getCorrectAnswer(), q.getAnswerDescription(),
                q.getPass(), q.getBelongToStudentId()));
    }

    private static List<MQuestion> allQuestions = new LinkedList<MQuestion>() {{
        add(new MQuestion(1L, "事物的价值是以（ ）为尺度的一种主客体统一的状态。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "主体", "略", true, 0L));
        add(new MQuestion(2L, "贫穷不是社会主义，是谁提出的？（ ）", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "邓小平", "略", true, 0L));
        add(new MQuestion(3L, "（ ）是信仰的目标化形象。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "理想", "略", true, 0L));
        add(new MQuestion(4L, "新的社会主义本质观是（ ）和真理统一的本质观。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "价值", "略", true, 0L));
        add(new MQuestion(5L, "社会主义价值体系的核心理念是什么？（ ）", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "公平", "略", true, 0L));
        add(new MQuestion(6L, "价值和价值观的问题在哲学上是在何时星期的一个新的哲学的基本理论分支？（  ）", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "十九世纪末二十世纪初", "略", true, 0L));
        add(new MQuestion(7L, "（ ）是价值观最核心、最实质的内容。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "信仰", "略", true, 0L));
        add(new MQuestion(8L, "人们关于基本价值的观念指的是（ ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "价值观念", "略", true, 0L));
        add(new MQuestion(9L, "先秦时期就提出了“和而不同”、“和合中庸”、“政通人和”、“天人合一”、“协和万邦”等丰富多彩、意蕴深远的（ ）理念。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "重和谐", "略", true, 0L));
        add(new MQuestion(10L, "科学发展观的核心是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "以人为本", "略", true, 0L));
        add(new MQuestion(11L, "（  ），是我们党面对多样化的思想文化，价值观念的一个基本原则。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "尊重差异，包容多样", "略", true, 0L));
        add(new MQuestion(12L, "社会主义民主是社会主义（  ）文明的重要标志。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "政治", "略", true, 0L));
        add(new MQuestion(13L, "职业道德的核心是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "敬业", "略", true, 0L));
        add(new MQuestion(14L, "（  ）反映了“中国梦”的实现道路：中国特色社会主义。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "倡导“富强、民主、文明、和谐”", "略", true, 0L));
        add(new MQuestion(15L, "“爱国、敬业、诚信、友善”反映了“中国梦”的实现主体（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "公民的德性和品格", "略", true, 0L));
        add(new MQuestion(16L, "近年来,我国加大在海外举办（ ）学院、文化交流中心和文艺演出、艺术活动等有效地在对外文化交往中传播社会主义核心价值观的重要作用。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "孔子", "略", true, 0L));
        add(new MQuestion(17L, "中国特色社会主义的总布局是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "经济、政治、文化、社会、生态文明建设“五位一体”", "略", true, 0L));
        add(new MQuestion(18L, "（  ）是社会主义道德建设的基础。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "社会公德", "略", true, 0L));
        add(new MQuestion(19L, "（  ）是公民个体道德化的摇篮。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "家庭美德", "略", true, 0L));
        add(new MQuestion(20L, "社会公德的内容不包括（  ）", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "邻里团结", "略", true, 0L));
        add(new MQuestion(21L, "职业道德的内容不包括（  ）", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "保护环境", "略", true, 0L));
        add(new MQuestion(22L, "（  ）是高尚的，是服务精神的精髓。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "奉献精神", "略", true, 0L));
        add(new MQuestion(23L, "全面提高党的建设科学化水平，全党要增强紧迫感和责任感，姥姥把握的主线是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "加强党的这正能力建设、先进性和纯洁性建设", "略", true, 0L));
        add(new MQuestion(24L, "开展党的群众路线教育实践活动，以（  ）为主要内容。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "为民务实厚德", "略", true, 0L));
        add(new MQuestion(25L, "中国共产党是根据自己的（  ），按照民主集中制组织起来的统一整体。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "纲领和章程", "略", true, 0L));
        add(new MQuestion(26L, "对马克思主义的信仰，对社会主义和共产主义的信念，是共产党人的（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "政治灵魂", "略", true, 0L));
        add(new MQuestion(27L, "党的十八届四中全会的主题是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "全面推进依法治国", "略", true, 0L));
        add(new MQuestion(28L, "党内（  ）是党的生命。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "民主", "略", true, 0L));
        add(new MQuestion(29L, "中国共产党的宗旨是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "全心全意为人民服务", "略", true, 0L));
        add(new MQuestion(30L, "2014件2月，习近平总书记在中央政治局第十三次集体学习时指出：“要把培育和弘扬（  ）作为凝魂聚气，强基固本的基础工程，作为一项根本任务，切实抓紧抓好。”", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "社会主义核心价值体系", "略", true, 0L));
        add(new MQuestion(31L, "党的基层组织是党在社会基层组织中的（  ），是党的全部工作和战斗力的基础。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "战斗堡垒", "略", true, 0L));
        add(new MQuestion(32L, "党的（  ）纪律是密切党羽群众血肉联系的重要保证。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "群众工作", "略", true, 0L));
        add(new MQuestion(33L, "（  ）是马克思主义政党的基本政治观点和根本工作路线。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "群众路线", "略", true, 0L));
        add(new MQuestion(34L, "民族精神的核心是爱国主义，时代精神的核心是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "改革创新", "略", true, 0L));
        add(new MQuestion(35L, "党的领导主要是（  ）的领导。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "政治、思想和组织", "略", true, 0L));
        add(new MQuestion(36L, "党的思想路线是一起从实际出发，理论联系实际，（  ），在实践中检验真理和发展真理。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "实事求是", "略", true, 0L));
        add(new MQuestion(37L, "党的群众路线教育实践活动要集中解决的“四风”问题是（  ）。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "形式主义、官僚主义、享乐主义、奢靡之风", "略", true, 0L));
        add(new MQuestion(38L, "协调推进“四个全面”的根本保证是（  ）。  ", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "全面从严治党", "略", true, 0L));
        add(new MQuestion(39L, "我们现在所提倡的（  ），内在的吸收了历史上所创造的一切思想精华，是对马克思主义人本价值理念认识的发展和深化，体现着价值尺度从“物”到“人”的转移。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "以人为本", "略", true, 0L));
        add(new MQuestion(40L, "建设社会主义核心价值体系，抓住了我国社会主义（  ）建设的关键和根本。", QuestionType.SingleChoice, QuestionClassification.Jiazhiguan, "文化建设", "略", true, 0L));
        add(new MQuestion(41L, "正义包括哪两种？（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "以公平为核心的正义, 以自由为核心的正义", "略", true, 0L));
        add(new MQuestion(42L, "社会主义本质的北韩包裹下列哪些？（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "最终达到共同富裕, 消除两极分化, 消除剥削, 解放生产力，发展生产力", "略", true, 0L));
        add(new MQuestion(43L, "党作为核心主题的价值观表现为哪两个层次？（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "代表全国人民表达和提出的价值观, 党自己的价值观", "略", true, 0L));
        add(new MQuestion(44L, "价值观念就是人们关于基本价值的（  ）的总和。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "信仰, 信念, 理想", "略", true, 0L));
        add(new MQuestion(45L, "社会主义核心价值观的基本特征，包括社会主义核心价值观的（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "包容性、民族性, 引领性、崇高性", "略", true, 0L));
        add(new MQuestion(46L, "加强职业道德建设的基本途径（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "完善内部职业规章制度，确保职业道德预警机制有序进行, 将职业行为纳入岗位考核体系，使道德规范具体化, 采取典型引路的方法，树立行业新风尚, 重视培养人们的职业情感", "略", true, 0L));
        add(new MQuestion(47L, "当代中国需要培育的国民心态包括（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "务实进取, 开放包容, 理性科学, 自尊自信", "略", true, 0L));
        add(new MQuestion(48L, "“讲文明、树新风”活动的具体包括以下内容（  ） ", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "大力倡导勤俭节约之风, 大力倡导文明礼仪之风, 大力倡导读书学习之风", "略", true, 0L));
        add(new MQuestion(49L, "创建文明城市、（  ）、（  ）是人民群众移风易俗、改造社会、建设美好生活的伟大创造。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "文明单位, 文明村镇", "略", true, 0L));
        add(new MQuestion(50L, "志愿精神的主要内容包括（  ）。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "互助精神, 友爱精神, 奉献精神, 进步精神", "略", true, 0L));
        add(new MQuestion(51L, "弘扬传统节日文化，发挥其所具有的强烈的（ ）认同感、（ ）认同感、（ ）认同感，能够最大限度地凝聚民心，有力地抵制西方文化的冲击和渗透。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "国家, 文化, 民族", "略", true, 0L));
        add(new MQuestion(52L, "目前，我国社会发展面对的挑战有（  ）。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "创新社会治理模式、维护社会和谐稳定, 执政方式和执政理念需要适应从革命党到执政党的变化, 转变经济发展方式刻不容缓的迫切性和严峻性", "略", true, 0L));
        add(new MQuestion(53L, "以下对树立政府和公共管理者的公共利益典范理解正确的是（  ）。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "改变整个社会道德, 要特别强调公共管理者意识, 首先是“官德”", "略", true, 0L));
        add(new MQuestion(54L, "培育和践行社会主义核心价值观的重大意义有（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "坚持和发展中国特色社会主义的内在要求, 增强国家软实力的根本要求, 新形势下引领社会思潮、凝聚社会共识的必然要求, 社会主义核心价值体系建设的最新发展", "略", true, 0L));
        add(new MQuestion(55L, "如何把培育和践行核心价值观融入国民教育全过程？（  ）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "充分发挥校园文化的熏陶作用, 充分发挥校园网络的引导作用, 充分发挥社会实践的养成作用, 充分发挥课堂教学的主渠道作用", "略", true, 0L));
        add(new MQuestion(56L, "十八大提出如何扎实推进社会主义文化强国？", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "丰富人民精神文化生活, 全面提高公民道德素质, 加强社会主义核心价值体系建设, 增强文化整体实力和竞争力", "略", true, 0L));
        add(new MQuestion(57L, "“中国梦”有哪些时代特征？（  ） ", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "中华文明在复兴中进一步演进的“文明特征”, 促进人全面发展的“价值特征”, 社会和谐进一步提升的“幸福特征”, 综合国力进一步跃升的“实力特征”", "略", true, 0L));
        add(new MQuestion(58L, "人的全面发展的基本内涵包括（  ）。", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "人的个性的自由发展, 人的活动的全面发展, 人的社会关系的全面发展, 人的素质全面提高", "略", true, 0L));
        add(new MQuestion(59L, "为什么说以爱国主义为核心的民族精神具有重大的现实意义和时代价值？（）", QuestionType.MultipleChoice, QuestionClassification.Jiazhiguan, "弘扬以爱国主义为核心的民族精神是提高全民族素质的基础工程, 是加强诚信建设的重要任务, 是引导人们树立正确理想、信念、人生观、价值观的共同基础, 是构建和谐社会的精神支撑", "略", true, 0L));
        add(new MQuestion(60L, "一切好与坏的现象都有一个根本特点、一个根本标准、一个根本前提、就是好与坏总是因人而异。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(61L, "主导价值观的建设是决定我们未来命运和前提的一件大事。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(62L, "现在价值论已经是哲学理论基础的正式组成部分。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(63L, "价值观的建设是事关党和国家的全局、国家和民族的命运全局的大事，是事关我们长远的大事。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(64L, "看待人的价值观念，更为重要的是理解人的社会存在。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(65L, "马克思主义价值论告诉我们，事物的价值是在主客观体关系中形成的，它是以主体为尺度的一种主客观体统一的状态。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(66L, "价值论就是探讨价值的本质规律的一个学科分支。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(67L, "科学发展观的核心是以人为本。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(68L, "事物的价值是以主体为尺度的一种主客体统一的状态。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(69L, "理想是信仰的目标化形象。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(70L, "新的社会主义本质观是价值和真理统一的本质观。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(71L, "社会主义价值体系的核心理念是公平。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(72L, "价值和价值观的问题在哲学上是在十九世纪末二十世纪初兴起的一个新的哲学的基本理论分支。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(73L, "信仰是价值观最核心、最实质的内容。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(74L, "人们关于基本价值的观念指的是价值观念。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(75L, "正义包括以自由为核心的正义和以公平为核心的正义。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(76L, "党作为核心主题的价值观表现为当自己的价值观。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "F", "党作为核心主题的价值观表现为党自己的价值观和代表全国人民表达和提出的价值观。", true, 0L));
        add(new MQuestion(77L, "价值观念就是人们关于基本价值的信念、信仰和理想的总和。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(78L, "社会公德是社会主义道德建设的基础。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(79L, "社会公德是公民个体道德化的摇篮。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "F", "家庭美德是公民个体道德化的摇篮。", true, 0L));
        add(new MQuestion(80L, "奉献精神是高尚的，是志愿服务精神的精髓。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(81L, "职业道德的内容仅包括保护环境。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "F", "职业道德的内容包括爱岗敬业、服务群众和奉献社会。", true, 0L));
        add(new MQuestion(82L, "以人与自然和谐为核心的生态文明是对工业文明反思的必然要求。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(83L, "贫穷是产生社会矛盾的重要根源，而发展则是促进社会和谐的基础。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(84L, "社会主义核心价值观必须广泛借鉴世界文明成果，符合人类最美好的价值追求。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(85L, "法律是硬约束、道德是软约束，要做到“法以诛恶，得意劝善”，而这功能能互补、相辅相成。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(86L, "“自由、平等、公正、法治”反映了“中国梦”的社会属性：资本主义性质。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "F", "“自由、平等、公正、法治”反映了“中国梦”的社会属性：社会主义性质。", true, 0L));
        add(new MQuestion(87L, "“诚”与“信”有着密切的联系。诚是人内在的德信，信则是诚的外在表现。诚于中，必信于外。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(88L, "维护社会公正是形成橄榄型社会的主要途径。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "T", "略", true, 0L));
        add(new MQuestion(89L, "社会主义民主是社会主义精神文明的重要标志。", QuestionType.TrueOrFalse, QuestionClassification.Jiazhiguan, "F", "社会主义民主是社会主义政治文明的重要标志。", true, 0L));
        add(new MQuestion(90L, "为什么要坚持马克思主义的指导地位？根本原因就在于马克思主义是社会主义核心价值观的（ ）。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "灵魂和精髓", "略", true, 0L));
        add(new MQuestion(91L, "（ ），是党领导人民治理国家的基本方略，是社会文明进步的重要标志。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "依法治国", "略", true, 0L));
        add(new MQuestion(92L, "（ ），为依法治国提供思想基础和精神支柱。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "增强法制观念", "略", true, 0L));
        add(new MQuestion(93L, "中华民族形成了以（  ）为核心的团结统一、爱好和平、勤劳勇敢、自强不息的伟大民族精神。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "爱国主义", "略", true, 0L));
        add(new MQuestion(94L, "爱国主义教育要抓住（ ）这个重点。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "广大青少年", "略", true, 0L));
        add(new MQuestion(95L, "倡导以（）、（）为主要内容的职业道德。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "爱岗敬业，奉献社会", "略", true, 0L));
        add(new MQuestion(96L, "以（）为核心的民族精神和以（）为核心的时代精神，是社会主义核心价值体系的精髓。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "爱国主义，改革创新", "略", true, 0L));
        add(new MQuestion(97L, "社会主义核心价值观必须立足（），符合广大人民群众的期待。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "中国特色社会主义伟大实践", "略", true, 0L));
        add(new MQuestion(98L, "社会主义核心价值观24字中，（）属于社会层面。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "自由、平等、公正、法治", "略", true, 0L));
        add(new MQuestion(99L, "社会主义核心价值观24字中，（）属于国家层面。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "富强、民主、文明、和谐", "略", true, 0L));
        add(new MQuestion(100L, "社会主义核心价值观24字中，（）属于个人层面。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "爱国、敬业、诚信、友善", "略", true, 0L));
        add(new MQuestion(101L, "志愿服务以（）、（）为前提，以弘扬志愿精神为核心。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "自愿、无偿", "略", true, 0L));
        add(new MQuestion(102L, "（）、（）、（）是我国党和政府处理民族关系的基本原则。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "民族平等、民族团结、各民族共同繁荣", "略", true, 0L));
        add(new MQuestion(103L, "大力整治交通秩序。全面开展“（）”，大力倡导六大文明交通行为，自觉摒弃六大交通陋习。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "文明交通行动计划", "略", true, 0L));
        add(new MQuestion(104L, "科学发展观的核心是（）。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "以人为本", "略", true, 0L));
        add(new MQuestion(105L, "（）是公民个体道德化的摇篮。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "家庭美德", "略", true, 0L));
        add(new MQuestion(106L, "（）是高尚的，是志愿服务精神的精髓。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "奉献精神", "略", true, 0L));
        add(new MQuestion(107L, "中国特色社会主义的总布局是（）。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "经济、政治、文化、社会、生态文明建设“五位一体”", "略", true, 0L));
        add(new MQuestion(108L, "（）是社会主义道德建设的基础", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "社会公德", "略", true, 0L));
        add(new MQuestion(109L, "弘扬传统节日文化，发挥其所具有的强烈的（）认同感、（）认同感、（）认同感，能够最大限度地凝聚民心，有力地抵制西方文化的冲击和渗透。", QuestionType.BlanksFilling, QuestionClassification.Jiazhiguan, "民族、文化、国家", "略", true, 0L));
        add(new MQuestion(110L, "党的（  ）通过的《关于社会主义精神文明建设指导方针的决议》，为加强社会主义精神文明建设制定了第一个纲领文件。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "十二届六中全会", "略", true, 0L));
        add(new MQuestion(111L, "“三个代表”重要思想是在科学判断（  ）基础上提出来的。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "党的历史地位", "略", true, 0L));
        add(new MQuestion(112L, "党的十六届四中全会通过了《中共中央关于（  ）的决定》。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "加强党的执政能力建设", "略", true, 0L));
        add(new MQuestion(113L, "河南省（  ）已列入《世界文化遗产名录》。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "洛阳龙门石窟", "略", true, 0L));
        add(new MQuestion(114L, "不说粗话脏话，不随地吐痰，不损坏公物，是符合（  ）的良好行为。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "社会公德", "略", true, 0L));
        add(new MQuestion(115L, "新的历史条件下，党执政的一个基本方式是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "依法执政", "略", true, 0L));
        add(new MQuestion(116L, "我国的基本经济制度是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "公有制为主体，多种所有制经济共同发展", "略", true, 0L));
        add(new MQuestion(117L, "人们接受道德教育最早的地点是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "家庭", "略", true, 0L));
        add(new MQuestion(118L, "党的十六大报告指出：必须尊重劳动力，尊重知识，尊重人才，尊重（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "创造", "略", true, 0L));
        add(new MQuestion(119L, "邓小平理论的精髓为（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "解放思想，实事求是", "略", true, 0L));
        add(new MQuestion(120L, "提高党的执政能力，关键在于搞好（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "党的建设", "略", true, 0L));
        add(new MQuestion(121L, "公民基本道德规范是：（  ）、明礼诚信、团结友善、勤俭自强、敬业奉献。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "爱国守法", "略", true, 0L));
        add(new MQuestion(122L, "公民道德建设的基本要求是爱祖国、爱人民、爱劳动、爱科学、（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "爱社会主义", "略", true, 0L));
        add(new MQuestion(123L, "（  ）是最活跃的、最革命的因素，是社会发展的最终决定力量。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "生产力", "略", true, 0L));
        add(new MQuestion(124L, "从未成年人抓起，培养和早就千千万万具有高尚思想品质和良好道德修养的合格（  ）和接班人，既是一项长远的战略任务，又是一项紧迫的的现实任务。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "建设者", "略", true, 0L));
        add(new MQuestion(125L, "包括（  ）在内的工人阶级、广大农民、始终是推动我国先进生产力发展和社会全面进步的根本力量。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "知识分子", "略", true, 0L));
        add(new MQuestion(126L, "有没有高昂的（  ），是衡量一个国家综合国力强弱的重要尺度。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "民族精神", "略", true, 0L));
        add(new MQuestion(127L, "河南省加强和改进未成年人思想道德建设总的活动载体是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "三优一争", "略", true, 0L));
        add(new MQuestion(128L, "科学发展观的本质和核心是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "坚持以人为本", "略", true, 0L));
        add(new MQuestion(129L, "中国共产党必须翅中代表中国先进生产力的发展要求，代表（  ），代表中国最广大人民的根本利益。这是对“三个代表”重要思想的集中概括。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "中国先进文化的前进方向", "略", true, 0L));
        add(new MQuestion(130L, "中共文明委确定每年的9月20日是（   ）宣传日。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "公民道德", "略", true, 0L));
        add(new MQuestion(131L, "“三个代表”重要思想的本质是：立党为公、（   ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "执政为民", "略", true, 0L));
        add(new MQuestion(132L, "“三讲一树”活动的内容是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "讲文明、讲卫生、讲科学、树新风", "略", true, 0L));
        add(new MQuestion(133L, "坚持最广泛、最充分地调动一切积极因素，不断提高构建社会主义（  ）的能力，是提高党的执政能力的任务之一。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "和谐社会", "略", true, 0L));
        add(new MQuestion(134L, " 党的十六大报告提出要“确立劳动、资本、技术和管理等生产要素按（  ）参与分配的原则。”", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "贡献", "略", true, 0L));
        add(new MQuestion(135L, "社会主义民主政治的本质是（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "人民当家作主", "略", true, 0L));
        add(new MQuestion(136L, "公民道德建设的过程，是教育和（  ）相结合的过程。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "实践", "略", true, 0L));
        add(new MQuestion(137L, "中国共产党最大的政治优势是（   ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "与时俱进", "略", true, 0L));
        add(new MQuestion(138L, "贯彻“三个代表”重要思想，关键在坚持与时俱进，核心在坚持党的先进性，本质在坚持（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "执政为民", "略", true, 0L));
        add(new MQuestion(139L, "我国非配制度中初次分配和再分配的原则是初次分配注重效率，发挥（  ）的作用，再分配注重公平。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "市场", "略", true, 0L));
        add(new MQuestion(140L, "在群众性精神文明创建活动中形成的三大创建活动是之创建文明城市、文明村镇、（   ）活动。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "文明行业", "略", true, 0L));
        add(new MQuestion(141L, "当今时代的主题是：（  ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "和平与发展", "略", true, 0L));
        add(new MQuestion(142L, "公民道德必须坚持社会主义道德建设与（  ）相适应的方针原则。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "社会主义市场经济", "略", true, 0L));
        add(new MQuestion(143L, "开展创建文明单位活动，要以（  ）为中心。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "生产经营和业务工作", "略", true, 0L));
        add(new MQuestion(144L, "全面建设小康社会的政治保证是（   ）。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "党的领导", "略", true, 0L));
        add(new MQuestion(145L, "提高党的执政能力，首先要提高党的领导（  ）的能力。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "发展", "略", true, 0L));
        add(new MQuestion(146L, "加强社会主义（  ），始发站下您文化的重要内容和中心环节。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "思想道德建设", "略", true, 0L));
        add(new MQuestion(147L, "发展先进文化，就是发展面向（  ）、面向世界、面向未来的，民族的科学的大众的社会主义文化。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "现代化", "略", true, 0L));
        add(new MQuestion(148L, "以（  ）为重点，这是十六大阐述加强思想道德建设是提出的一个重要论断。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "诚实守信", "略", true, 0L));
        add(new MQuestion(149L, "（  ）是人民群众移风易俗、改造社会的伟大创造。", QuestionType.SingleChoice, QuestionClassification.Daodepingjia, "群众性精神文明创建活动", "略", true, 0L));
        add(new MQuestion(150L, "社会主义精神文明建设包括（  ）、（  ）两个方面的内容。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "思想道德建设, 教育科学文化建设", "略", true, 0L));
        add(new MQuestion(151L, "在中国八大古都中，河南省有洛阳、（  ）、（  ）、（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "安阳, 开封, 郑州", "略", true, 0L));
        add(new MQuestion(152L, "“三讲一树”活动的内容是（  ）、（  ）、（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "讲卫生, 讲文明, 讲科学", "略", true, 0L));
        add(new MQuestion(153L, "“四进社区”指的是“科教、（  ）、（  ）、（  ）”进社区。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "卫生, 文体, 法律", "略", true, 0L));
        add(new MQuestion(154L, "河南新石器时代的代表文明是（  ）、（  ）、（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "仰韶文化, 裴李岗文化, 龙山文化", "略", true, 0L));
        add(new MQuestion(155L, "科学发展观的主要内容包括：（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "全面发展观, 协调发展观, 可持续发展观", "略", true, 0L));
        add(new MQuestion(156L, "未成年人思想建设的三个环节是：（   ）", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "学校, 家庭, 社会", "略", true, 0L));
        add(new MQuestion(157L, "我国政府主张海峡两岸尽快实现的“三通”是指（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "通商, 通航, 通邮", "略", true, 0L));
        add(new MQuestion(158L, "公民道德建设的着力点是（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "家庭美德, 社会公德, 职业道德", "略", true, 0L));
        add(new MQuestion(159L, "文明单位是社会主义（  ）建设中的综合性荣誉称号。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "政治文明, 物质文明, 精神文明", "略", true, 0L));
        add(new MQuestion(160L, "共产党要将修养的原因包括（   ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "为了保持我们无产阶级的先锋战士的纯洁，必须讲修养, 为了克服党内各种错误，必须讲修养, 为了实现改造社会的任务，必须将修养, 革命者要改造和提高自己，必须讲修养", "略", true, 0L));
        add(new MQuestion(161L, "温家宝说：“道德是世界上最伟大的，她的光芒甚至比太阳还要灿烂。”此论述表达了（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "道德具有崇高性, 道德要求即有无私性和利他性", "略", true, 0L));
        add(new MQuestion(162L, "我国古代官员道德建设有一套较为完整的保障制度，包括（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "以科举为主要形式的选任制度, 定期考核制度, 法律制度, 监督制度", "略", true, 0L));
        add(new MQuestion(163L, "我国古代官德大致包括（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "信, 廉, 慎, 正", "略", true, 0L));
        add(new MQuestion(164L, "“正”是我国古代官员职业道德的重要内容，其含义有（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "为人正直，大公无私, 处事公正，不偏不倚", "略", true, 0L));
        add(new MQuestion(165L, "“慎”是我国古代官员职业道德的重要内容，其含义有（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "“慎交”，即谨慎交友, 慎独, 慎言", "略", true, 0L));
        add(new MQuestion(166L, "《公务员法》将公务员的基本素质要求归结为五大方面，除了勤、绩之外，还包括（  ）方面。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "廉, 德, 能", "略", true, 0L));
        add(new MQuestion(167L, "行政伦理是政府行政过程中所应当确立和遵守的伦理价值、原则和规范，它是整个政府管理的价值观念体系，包括以下层次：（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "行政人员的个人道德, 行政机构的组织伦理, 行政管理的职业道德, 行政过程的伦理政策", "略", true, 0L));
        add(new MQuestion(168L, "共产党员修养的主要内容包括（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "要有无产阶级的思想意识和道德品质的修养, 要有无产阶级的革命战略、战术的修养, 要有马克思列宁主义理论的修养", "略", true, 0L));
        add(new MQuestion(169L, "公务员的职业纪律就类别来说，有（  ）。", QuestionType.MultipleChoice, QuestionClassification.Daodepingjia, "工作纪律, 廉政纪律, 政治纪律", "略", true, 0L));
        add(new MQuestion(170L, "党必须始终紧紧抓住发展这个执政兴国的第一要务。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(171L, "任何时候都不能以牺牲精神文明为代价换区经济一时的发展。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(172L, "社会主义道德风尚的形成，巩固和发展，要考教育们也要靠法制。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(173L, "开展创建文明单位活动，要以生产经营和业务工作为中心。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(174L, "文明单位是社会主义物质文明、政治文明、精神文明建设中的综合性荣誉称号。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(175L, "有没有高昂的民族精神，是衡量一个国家综合实力强弱的重要尺度。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(176L, "爱国主义和社会主义本质上是一致的。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(177L, "在改革发展稳定的关系中，稳定是前提、改革是动力、发展是目的。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(178L, "科学发展观就是以人为本、全面发展，协调发展和可持续发展。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(179L, "公民道德建设必须坚持注重效率与维护社会公平相协调。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(180L, "社会主义道德建设的原则是集体主义。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(181L, "公有制实现形式可以而且应当多样化。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(182L, "公民道德建设过程是教育和时间相结合的过程。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(183L, "思想道德建设是社会主义精神文明建设的中心环节。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(184L, "精神文明建设必须紧紧围绕经济建设这个中心。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(185L, "党的领导是依法治国的根本保证。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(186L, "改革是全面的改革，既包括体制层面又包括思想观念层面。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(187L, "公民道德建设必须坚持继承优良传统和发扬时代精神相结合。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(188L, "坚持注重效率与维护社会公平相协调是公民道德建设的一个重要方针原则。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(189L, "社会主义精神文明建设实社会主义社会的重要特征。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "T", "略", true, 0L));
        add(new MQuestion(190L, "群众性精神文明建设，要从创建文明家庭这个社会细胞开始。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "群众性精神文明建设，要从优化家庭这个社会细胞开始。", true, 0L));
        add(new MQuestion(191L, "建设精神文明的关键在人民。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "建设精神文明的关键在党。", true, 0L));
        add(new MQuestion(192L, "公民道德建设的原则是社会公德。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "公民道德建设的原则是集体主义。", true, 0L));
        add(new MQuestion(193L, "生产力和生产关系是社会基本矛盾。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "生产力和生产关系、经济基础和上层建筑的矛盾是社会基本矛盾。", true, 0L));
        add(new MQuestion(194L, "思想道德教育是人民群众移风易俗、改造社会的伟大创造。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "群众性精神文明创建活动是人民群众移风易俗、改造社会的伟大创造。", true, 0L));
        add(new MQuestion(195L, "加强社会主义文学艺术事业，是发展先进文化的重要内容和中心环节。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "加强社会主义思想道德建设，是发展先进文化的重要内容和中心环节。", true, 0L));
        add(new MQuestion(196L, "未成年人思想建设的三个环节是：学校、家庭、单位。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "未成年人思想建设的三个环节是：学校、家庭、社会。", true, 0L));
        add(new MQuestion(197L, "全面建设小康社会的政治保证是政治文明。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "全面建设小康社会的政治保证是党的领导。", true, 0L));
        add(new MQuestion(198L, "科学发展观的主要内容包括：全面发展观、协调发展观和跨越发展观。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "科学发展观的主要内容包括：全面发展观、协调发展观和可持续发展观。", true, 0L));
        add(new MQuestion(199L, "公民道德建设的过程，是教育和监督相结合的过程。", QuestionType.TrueOrFalse, QuestionClassification.Daodepingjia, "F", "公民道德建设的过程，是教育和实践相结合的过程。", true, 0L));
        add(new MQuestion(200L, "面对世界范围各种思想文化的相互激荡，必须把弘扬和培育（  ）作为文化建设即为重要的任务，纳入精神文明建设全过程。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "民族精神", "略", true, 0L));
        add(new MQuestion(201L, "“四进社区”指的是（  ）、文体、法律、卫生进社区。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "科教", "略", true, 0L));
        add(new MQuestion(202L, "公民基本道德规范是：爱国守法、（  ）、团结友善、勤俭自强、敬业奉献。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "明礼诚信", "略", true, 0L));
        add(new MQuestion(203L, "我们进行的精神文明建设，是以经济建设为中心，坚持四项基本原则和坚持（  ）的精神文明建设。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "改革开放", "略", true, 0L));
        add(new MQuestion(204L, "将强和改进未成年人思想道德建设，要把（  ）与社会教育、学校教育紧密结合起来。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "家庭教育", "略", true, 0L));
        add(new MQuestion(205L, "群众性精神文明创建活动始于20世纪80年代初全国各地开展的（  ）活动。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "五讲四美三热爱", "略", true, 0L));
        add(new MQuestion(206L, "开展创建文明城市活动要以提高市民（  ）和城市文明程度为目标。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "文明素质", "略", true, 0L));
        add(new MQuestion(207L, "“三个代表”重要思想的本质是立党为公、（   ）。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "执政为民", "略", true, 0L));
        add(new MQuestion(208L, "（  ）是我们党的立党之本、执政之基、力量之源。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "“三个代表”重要思想", "略", true, 0L));
        add(new MQuestion(209L, "要大力倡导以爱岗敬业、诚实守信、（  ）、服务群众、奉献社会为主要内容分的职业道德。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "办事公道", "略", true, 0L));
        add(new MQuestion(210L, "全面推进党的建设新的伟大工程，必须以提高党的（  ）为重点。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "执政能力", "略", true, 0L));
        add(new MQuestion(211L, "发展是党执政兴国的（  ）。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "第一要务", "略", true, 0L));
        add(new MQuestion(212L, " 在群众性精神文明创建活动中形成的三大创建活动是：创建（  ）、创建文明村镇和创建文明行业活动。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "文明城市", "略", true, 0L));
        add(new MQuestion(213L, "要大力倡导以文明礼貌、助人为乐、爱护公物、（  ）、遵纪守法为主要内容的社会公德。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "保护环境", "略", true, 0L));
        add(new MQuestion(214L, "在五千多年的发展中，中华民族形成了以（  ）为核心的伟大民族精神。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "爱国主义", "略", true, 0L));
        add(new MQuestion(215L, "新时期中国最鲜明的特征是（  ）。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "改革开放", "略", true, 0L));
        add(new MQuestion(216L, "（  ）是社会主义的自我完善和发展，是经济和社会发展的强大动力。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "改革", "略", true, 0L));
        add(new MQuestion(217L, "要大力倡导以尊老爱幼、男女平等、夫妻和睦、勤俭持家、（  ）为主要内容的家庭美德。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "邻里团结", "略", true, 0L));
        add(new MQuestion(218L, "公民道德建设必须坚持尊重个人合法权益与承担（  ）相统一。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "社会责任", "略", true, 0L));
        add(new MQuestion(219L, "公民道德建设要坚持先进性要求和（  ）要求相结合。", QuestionType.BlanksFilling, QuestionClassification.Daodepingjia, "广泛性", "略", true, 0L));
        add(new MQuestion(220L, "标志着中国新民主主义革命开端的历史事件是( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "五四运动", "略", true, 0L));
        add(new MQuestion(221L, "1921年7月23日至8月初，中国共产党第一次全国代表大会先后在( )召开。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "上海、嘉兴", "略", true, 0L));
        add(new MQuestion(222L, "第一次明确提出彻底的反帝反封建民主革命纲领的会议是( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "中共二大", "略", true, 0L));
        add(new MQuestion(223L, "第一次国共合作正式建立的标志是( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "国民党第一次全国代表大会的召开", "略", true, 0L));
        add(new MQuestion(224L, "标志着中国共产党开始独立领导革命战争和创建人民军队的事件是( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "南昌起义", "略", true, 0L));
        add(new MQuestion(225L, "“政权是由枪杆子中取得的”这一论断是毛泽东在( )提出的。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "八七会议上", "略", true, 0L));
        add(new MQuestion(226L, "( )从组织上确立了党对军队的绝对领导，为建立一支无产阶级领导下的新型人民军队奠定了基础。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "三湾改编", "略", true, 0L));
        add(new MQuestion(227L, "红军长征途中召开的( )，开始确立了毛泽东在党中央和红军的领导地位，挽救了党、挽救了红军、挽救了中国革命，成为党的历史上一个生死攸关的转折点。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "遵义会议", "略", true, 0L));
        add(new MQuestion(228L, "1935年12月，中共中央在( C)上确定了抗日民族统一战线的策略方针。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "瓦窑堡会议", "略", true, 0L));
        add(new MQuestion(229L, "1937年( )事变爆发，全面抗战由此开始。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "卢沟桥", "略", true, 0L));
        add(new MQuestion(230L, "全面抗战爆发后，八路军打的第一个大胜仗是()。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "平型关大捷", "略", true, 0L));
        add(new MQuestion(231L, "1940年8月至12月，八路军在华北发动的()，给日军以沉重打击。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "百团大战", "略", true, 0L));
        add(new MQuestion(232L, "1942年5月，八路军副参谋长( )在指挥八路军总部进行反“扫荡”战斗时，不幸中弹，壮烈殉国。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "左权", "略", true, 0L));
        add(new MQuestion(233L, "“千古奇冤，江南一叶;同室操戈，相煎何急?”是周恩来在( )后对国民党蒋介石的控诉和回击。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "皖南事变", "略", true, 0L));
        add(new MQuestion(234L, "抗日战争时期，被中共中央誉为“敌后模范的抗日根据地及统一战线的模范区”的是( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "晋察冀抗日根据地", "略", true, 0L));
        add(new MQuestion(235L, "1945年(", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "，日本代表在投降书上签字，日军128万人向中国投降。至此，中国抗日战争胜利结束，世界反法西斯战争也胜利结束。", "略", true, 0L));
        add(new MQuestion(236L, "1945年，党的( )确立了毛泽东思想为全党的指导思想。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "七大", "略", true, 0L));
        add(new MQuestion(237L, "抗日战争胜利后，国共双方举行了最高级别谈判，双方代表签署了《政府与中共代表会谈纪要》，这就是历史上著名的( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "重庆谈判", "略", true, 0L));
        add(new MQuestion(238L, "国民党发动全面内战是从1946年进攻( )解放区开始的。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "中原", "略", true, 0L));
        add(new MQuestion(239L, "1946年8月，毛泽东在同美国记者安娜·路易斯·斯特朗的谈话中提出了( )。", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "“帝国主义和一切反动派都是纸老虎”", "略", true, 0L));
        add(new MQuestion(240L, "吸收（ ）以下的青年入党，一般应是共青团员。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "28周岁", "略", true, 0L));
        add(new MQuestion(241L, "“特别能吃苦、特别能攻关、特别能战斗、特别能奉献”，指的是(   )。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "载人航天精神", "略", true, 0L));
        add(new MQuestion(242L, "2000年2月25日，江泽民在广州考察工作时提出(    )重要思想。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "“三个代表”", "略", true, 0L));
        add(new MQuestion(243L, "（ ），中国共产党第一次全国代表大会在上海举行。   ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "1921年7月23日；", "略", true, 0L));
        add(new MQuestion(244L, "(   )是决定一个政党、一个政权盛衰的根本因素。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "人心向背", "略", true, 0L));
        add(new MQuestion(245L, "改革的实质是(    )。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "体制创新", "略", true, 0L));
        add(new MQuestion(246L, "一个政党的(    )就是一面旗帜。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "纲领", "略", true, 0L));
        add(new MQuestion(247L, "党内(    )是党的生命，对人民民主具有重要的示范和带动作用。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "民主", "略", true, 0L));
        add(new MQuestion(248L, "(    )是我们党的基本政治观点。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "群众观点", "略", true, 0L));
        add(new MQuestion(249L, "支部党员大会，到会正式党员超过支部应到正式党员（  ）以上，会议有 效。   ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "二分之一；", "略", true, 0L));
        add(new MQuestion(250L, "支部党员大会表决议案，赞成票超过支部应到有表决权党员的人数（  ）以上，表决通过。   ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "二分之一；", "略", true, 0L));
        add(new MQuestion(251L, "支部党员大会，一般（  ）至少召开一次。 ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "每季；", "略", true, 0L));
        add(new MQuestion(252L, "党课教育，一般每季度（  ）。   ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "一次；", "略", true, 0L));
        add(new MQuestion(253L, "支委会，一般每季度召开（  ），也可根据工作需要随时召开。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "一次；", "略", true, 0L));
        add(new MQuestion(254L, "党员选举大会，到会有选举权的正式党员超过应到有选举权的正式党员 （  ）以上，选举大会有效。   ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "五分之四", "略", true, 0L));
        add(new MQuestion(255L, "党内选举时，当选人应获得到会有选举权的正式党员赞成票数（  ）以上，始得当选。   ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "二分之一；", "略", true, 0L));
        add(new MQuestion(256L, "至少有正式党员（  ）的机关(单位)，可以单独建立党支部。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "3-7人；", "略", true, 0L));
        add(new MQuestion(257L, "有党员（  ）的机关(单位)，可以成立党支部委员会。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "7人至50人；", "略", true, 0L));
        add(new MQuestion(258L, "有党员（  ）的机关（单位），可以成立党总支部委员会。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "50人至100人", "略", true, 0L));
        add(new MQuestion(259L, "有党员（ ）的机关（单位），可以成立党的基层委员会。  ", QuestionType.SingleChoice, QuestionClassification.Lilunjichu, "100人以上；", "略", true, 0L));
        add(new MQuestion(260L, "中国共产党领导全国各族人民，经过长期的反对(    )的革命斗争，取得了新民主主义革命的胜利。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "官僚资本主义, 封建主义, 帝国主义", "略", true, 0L));
        add(new MQuestion(261L, "始终做到“三个代表”，是我们党的(    )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "力量之源, 执政之基, 立党之本", "略", true, 0L));
        add(new MQuestion(262L, "各项工作都要把(    )作为总的出发点和检验标准。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "有利于发展社会主义社会的生产力, 有利于增强社会主义国家的综合国力, 有利于提高人民的生活水平", "略", true, 0L));
        add(new MQuestion(263L, "党章规定，党的建设必须(    )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "坚持党的基本路线, 坚持全心全意为人民服务, 坚持民主集中制, 坚持解放思想，实事求是，与时俱进", "略", true, 0L));
        add(new MQuestion(264L, "党的领导主要是(    )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "思想的领导, 政治的领导, 组织的领导", "略", true, 0L));
        add(new MQuestion(265L, "党章指出，要在党内造成(    )的生动活泼的政治局面。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "又有纪律又有自由, 又有统一意志又有个人心情舒畅, 又有集中又有民主", "略", true, 0L));
        add(new MQuestion(266L, "当前和今后一个时期，党发展党员工作的方针是(    )。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "保证质量, 坚持标准, 慎重发展, 改善结构", "略", true, 0L));
        add(new MQuestion(267L, "党章规定，党的组织系统是由(    )组成的。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "中央组织, 地方组织, 基层组织", "略", true, 0L));
        add(new MQuestion(268L, "党支部的“三会一课”制度的“三会”指的是(    )。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "党员大会, 党小组会, 支部委员会", "略", true, 0L));
        add(new MQuestion(269L, "贯彻“三个代表”重要思想(    )  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "关键在坚持与时俱进, 本质在坚持执政为民, 核心在坚持党的先进性", "略", true, 0L));
        add(new MQuestion(270L, "创新是(    )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "一个国家兴旺发达的不竭动力, 一个政党永葆生机的源泉, 一个民族进步的灵魂", "略", true, 0L));
        add(new MQuestion(271L, "当前和今后一个时期，要抓住重点，集中解决党的(    )和干部生活作风方面的突出问题。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "学风, 工作作风, 思想作风, 领导作风", "略", true, 0L));
        add(new MQuestion(272L, "毛泽东思想的活的灵魂是(  )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "实事求是, 独立自主, 群众路线", "略", true, 0L));
        add(new MQuestion(273L, "党取得新民主主义革命胜利的三大法宝是(    )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "党的建设, 武装斗争, 统一战线", "略", true, 0L));
        add(new MQuestion(274L, "在解放战争时期，党领导了(    )三大战役，取得了解放战争的决定性胜利。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "平津战役, 淮海战役, 辽沈战役", "略", true, 0L));
        add(new MQuestion(275L, "进入新世纪，(    )是我们党必须抓好的三大任务。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "完成祖国统一, 继续推进现代化建设, 维护世界和平与促进共同发展", "略", true, 0L));
        add(new MQuestion(276L, "党章规定，党员如果没有正当理由，(  )就被认为是自行脱党。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "或不交纳党费, 或不做党所分配的工作, 连续六个月不参加党的组织生活", "略", true, 0L));
        add(new MQuestion(277L, "相信谁、依靠谁、为了谁，是否始终站在最广大人民的立场上(    )。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "是判断马克思主义政党的试金石, 是区分唯物史观和唯心史观的分水岭", "略", true, 0L));
        add(new MQuestion(278L, "全面贯彻落实“三个代表”重要思想(   )。 ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "关系中华民族的伟大复兴, 关系中国特色社会主义事业的长远发展, 关系党和国家工作的全局, 关系实现全面建设小康社会的宏伟目标", "略", true, 0L));
        add(new MQuestion(279L, "党的作风(    )。  ", QuestionType.MultipleChoice, QuestionClassification.Lilunjichu, "关系人心向背, 关系党的形象, 关系党的生命", "略", true, 0L));
        add(new MQuestion(280L, "中国共产党的宗旨是全心全意为人民服务。", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "全心全意为人民服务", true, 0L));
        add(new MQuestion(281L, "党领导人民在建设社会主义物质文明和政治文明的同时，努力建设社会主义精神文明。  ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "政治文明", true, 0L));
        add(new MQuestion(282L, "党的中央委员会每届任期三年。  ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "五", true, 0L));
        add(new MQuestion(283L, "党员的党龄，从支部大会通过其为预备党员之日算起。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "预备期满转为正式党员", true, 0L));
        add(new MQuestion(284L, "中国共产党党员标准主要是由党的工人阶级先锋队性质决定的。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "党的工人阶级先锋队性质   ", true, 0L));
        add(new MQuestion(285L, "共产党的党性是工人阶级的阶级性的最高表现。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "工人阶级的阶级性  ", true, 0L));
        add(new MQuestion(286L, "党的团结的政治基础是党的纲领路线 。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "党的纲领路线 ", true, 0L));
        add(new MQuestion(287L, "党的团结的思想基础是民主集中制。  ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "马克思主义", true, 0L));
        add(new MQuestion(288L, "党的团结的组织基础是马克思主义。  ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "民主集中制 ", true, 0L));
        add(new MQuestion(289L, "“只有以先进理论为指南的党，才能实现先进战士的作用。”这一著名论断是由列宁提出来的。     ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "列宁", true, 0L));
        add(new MQuestion(290L, "推进党的思想建设，核心是保持党同人民群众的血肉联系。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "作风", true, 0L));
        add(new MQuestion(291L, "党的八大，把毛泽东思想确立为党的指导思想。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "七大", true, 0L));
        add(new MQuestion(292L, "党的十五大，把邓小平理论确立为党的指导思想。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "十五大", true, 0L));
        add(new MQuestion(293L, "一九一九年五四运动标志着中国新民主主义革命的开端。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "新民主主义革命", true, 0L));
        add(new MQuestion(294L, "党的一大，选举毛泽东 为中央局书记。          ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "陈独秀", true, 0L));
        add(new MQuestion(295L, "南昌起义打响了党武装反抗国民党反动派的第一枪。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", " 南昌起义", true, 0L));
        add(new MQuestion(296L, "遵义会议 确立了毛泽东在党和红军中的领导地位，在极其危急的情况下挽救了党，挽救了红军，挽救了中国革命。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "遵义会议", true, 0L));
        add(new MQuestion(297L, "毛泽东指出，思想路线 确定之后，干部就是决定因素。         ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "政治路线", true, 0L));
        add(new MQuestion(298L, "1997年7月1日 中国对香港恢复行使主权。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "1997年7月1日", true, 0L));
        add(new MQuestion(299L, "十六届三中全会通过了《中共中央关于经济体制改革的决定》。  ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "《中共中央关于完善社会主义市场经济体制若干问题的决定》", true, 0L));
        add(new MQuestion(300L, "人民解放战争的战略反攻开始于刘邓、陈谢、陈粟三军驰骋中原。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "刘邓、陈谢、陈粟三军驰骋中原", true, 0L));
        add(new MQuestion(301L, "1947年7月至9月，在毛泽东主持下，中共中央工作委员会在河北平山县西柏坡召开全国土地会议，制定了《中国土地法大纲》。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "刘少奇", true, 0L));
        add(new MQuestion(302L, "1947年11月12日石门的解放，使晋察冀和晋冀鲁豫两大解放区连成一片。周恩来对此给予了高度的评价，称之为“夺取大城市之创例”，并以《喜闻收复石门》为题赋诗祝贺。    ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "朱德", true, 0L));
        add(new MQuestion(303L, "1948年8月7日至19日，在中国民主历程中具有重要意义的华北临时人民代表大会在石家庄人民礼堂隆重召开。9月20日至24日，华北人民政府委员会在石家庄召开全体会议，董必武当选政府主席。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "董必武 ", true, 0L));
        add(new MQuestion(304L, "1949年3月，中共中央在北京召开七届二中全会。毛泽东在会上向全党同志提出了著名的“两个务必”。  F  西柏坡", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "西柏坡", true, 0L));
        add(new MQuestion(305L, "1949年9月21日，中国人民政治协商会议第一届全体会议在北平隆重开幕。毛泽东在开幕词中庄严地宣告：“占人类总数四分之一的中国人从此站立起来了。”  ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "中国人民政治协商会议", true, 0L));
        add(new MQuestion(306L, "1950年6月朝鲜战争爆发，10月19日以彭德怀为司令员兼政治委员的中国人民志愿军奉命开赴朝鲜战场。   ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "彭德怀 ", true, 0L));
        add(new MQuestion(307L, "1954年9月15日至28日，第一届全国人民代表大会第一次会议在北京隆重召开。大会通过了《中华人民共和国宪法》，以根本大法的形式，把中国共产党在过渡时期的总路线作为国家在过渡时期的总任务确定下来。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "《中华人民共和国宪法》", true, 0L));
        add(new MQuestion(308L, "1954年底，社会主义改造取得决定性的胜利，基本消灭了剥削制度，全民所有制和劳动群众集体所有制这两种社会主义公有制形式，已在国民经济中占据绝对优势地位。 F  1956", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "1956", true, 0L));
        add(new MQuestion(309L, "1956年4月，毛泽东发表《论人民民主专政》，初步提出了中国社会主义建设的基本方针，就是要把国内外一切积极因素调动起来，为社会主义事业服务。 ", QuestionType.TrueOrFalse, QuestionClassification.Lilunjichu, "T", "《论十大关系》", true, 0L));
        add(new MQuestion(310L, "贯彻创新、协调、绿色、开放、共享的发展理念不力，对职责范围内的问题失察失责，造成较大损失或者重大损失的，（ ）处分。   ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "从重或者加重", "略", true, 0L));
        add(new MQuestion(311L, "在上级检查、视察工作或者向上级汇报、报告工作时纵容、唆使、暗示、强迫下级说假话、报假情的，（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "从重或者加重", "略", true, 0L));
        add(new MQuestion(312L, "在党的纪律检查、组织、宣传、统一战线工作以及机关工作等其他工作中，不履行或者不正确履行职责，造成损失或者不良影响的，应当视具体情节给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "警告直至开除党籍", "略", true, 0L));
        add(new MQuestion(313L, "党员领导干部不重视家风建设，对配偶、子女及其配偶失管失教，造成不良影响或者严重后果的，给予警告或者严重警告处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务", "略", true, 0L));
        add(new MQuestion(314L, "违背社会公序良俗，在公共场所有不当行为，造成不良影响的，给予（ ）处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "警告或者严重警告", "略", true, 0L));
        add(new MQuestion(315L, "对信仰宗教的党员，应当加强思想教育，经党组织帮助教育仍没有转变的，应当（ ）；劝而不退的，予以（ ）；参与利用宗教搞煽动活动的，给予开除党籍处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "勒令退党", "略", true, 0L));
        add(new MQuestion(316L, "党员领导干部对违反政治纪律和政治规矩等错误思想和行为不报告、不抵制、不斗争，放任不管，搞无原则一团和气，造成不良影响的，给予警告或者严重警告处分；情节严重的，给予（ ）处分。   ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务或者留党察看", "略", true, 0L));
        add(new MQuestion(317L, "在干部选拔任用工作中，有任人唯亲、排斥异己、封官许愿、说情干预、跑官要官、突击提拔或者调整干部等违反干部选拔任用规定行为，对直接责任者和领导责任者，情节较轻的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "开除党籍", "略", true, 0L));
        add(new MQuestion(318L, "驻外机构或者临时出国（境）团（组）中的党员，脱离组织出走时间不满（ ）又自动回归的，给予撤销党内职务或者留党察看处分；脱离组织出走时间超过（ ）的，按照自行脱党处理，党内予以除名。", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "三个月", "略", true, 0L));
        add(new MQuestion(319L, "收受可能影响公正执行公务的礼品、礼金、消费卡和（ ）等财物，情节较轻的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。   ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "有价证券、股权、其他金融产品", "略", true, 0L));
        add(new MQuestion(320L, "向从事公务的人员及其配偶、子女及其配偶等亲属和其他特定关系人赠送明显超出正常礼尚往来的礼品、礼金、消费卡和（ ）等财物，情节较重的，给予警告或者严重警告处分；情节严重的，给予撤销党内职务或者留党察看处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "有价证券、股权、其他金融产品", "略", true, 0L));
        add(new MQuestion(321L, "利用职权或者职务上的影响，违反有关规定占用公物归个人使用，时间超过（ ），情节较重的，给予警告或者严重警告处分；情节严重的，给予撤销党内职务处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "六个月", "略", true, 0L));
        add(new MQuestion(322L, "利用宗族或者黑恶势力等欺压群众，或者纵容涉黑涉恶活动，为黑恶势力充当“保护伞”的，给予（ ）处分；情节严重的，给予开除党籍处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务或者留党察看", "略", true, 0L));
        add(new MQuestion(323L, "盲目举债、铺摊子、上项目，搞劳民伤财的“形象工程”“政绩工程”，致使国家、集体或者群众财产和利益遭受较大损失的，对直接责任者和领导责任者，给予（ ）处分；情节严重的，给予撤销党内职务、留党察看或者开除党籍处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "警告或者严重警告", "略", true, 0L));
        add(new MQuestion(324L, "在重大原则问题上，不同党中央保持一致且有实际言论、行为或者造成不良后果的，给予（ ）处分；情节较重的，给予（ ）处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "严重警告", "略", true, 0L));
        add(new MQuestion(325L, "通过网络、广播、电视、报刊、传单、书籍等，或者利用讲座、论坛、报告会、座谈会等方式，公开发表坚持资产阶级自由化立场、反对四项基本原则，反对党的改革开放决策的文章、演说、宣言、声明等的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "开除党籍", "略", true, 0L));
        add(new MQuestion(326L, "在党内组织秘密集团或者组织其他分裂党的活动的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "开除党籍", "略", true, 0L));
        add(new MQuestion(327L, "党员领导干部在本人主政的地方或者分管的部门自行其是，搞山头主义，拒不执行党中央确定的大政方针，甚至背着党中央另搞一套的，给予（ ）处分。   ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务、留党察看或者开除党籍处分", "略", true, 0L));
        add(new MQuestion(328L, "落实党中央决策部署不坚决，打折扣、搞变通，在政治上造成不良影响或者严重后果的，给予警告或者严重警告处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务、留党察看或者开除党籍处分", "略", true, 0L));
        add(new MQuestion(329L, "对党不忠诚不老实，表里不一，阳奉阴违，欺上瞒下，搞两面派，做两面人，情节较轻的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "开除党籍", "略", true, 0L));
        add(new MQuestion(330L, "制造、散布、传播政治谣言，破坏党的团结统一的，给予警告或者严重警告处分；情节较重的，给予（ ）处分；情节严重的，给予开除党籍处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务或者留党察看", "略", true, 0L));
        add(new MQuestion(331L, "擅自对应当由党中央决定的重大政策问题作出决定、对外发表主张的，对直接责任者和领导责任者，给予严重警告或者撤销党内职务处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "留党察看或者开除党籍", "略", true, 0L));
        add(new MQuestion(332L, "不按照有关规定向组织请示、报告重大事项，情节较重的，给予警告或者严重警告处分；情节严重的，给予（ ）处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务或者留党察看", "略", true, 0L));
        add(new MQuestion(333L, "干扰巡视巡察工作或者不落实巡视巡察整改要求，情节较轻的，给予警告或者严重警告处分；情节较重的，给予（ ）处分；情节严重的，给予开除党籍处分。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "撤销党内职务或者留党察看", "略", true, 0L));
        add(new MQuestion(334L, "党员受到警告处分（ ）、受到严重警告处分（ ），不得在党内提升职务和向党外组织推荐担任高于其原任职务的党外职务。   ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "一年内", "略", true, 0L));
        add(new MQuestion(335L, "留党察看处分，分为留党察看（ ）、留党察看（ ）。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "二年", "略", true, 0L));
        add(new MQuestion(336L, "党员受到开除党籍处分，（ ）内不得重新入党，也不得推荐担任与原任职务相当或者高于其原任职务的党外职务。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "五年内", "略", true, 0L));
        add(new MQuestion(337L, "党组织在纪律审查中发现党员严重违纪涉嫌违法犯罪的，原则上先作出（ ）决定，并按照规定给予政务处分后，再移送有关国家机关依法处理。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "党纪处分", "略", true, 0L));
        add(new MQuestion(338L, "党员被依法（ ）、逮捕的，党组织应当按照管理权限中止其表决权、选举权和被选举权等党员权利。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "留置", "略", true, 0L));
        add(new MQuestion(339L, "《中国共产党纪律处分条例》所称主动交代，是指涉嫌违纪的党员在组织初核（ ）向有关组织交代自己的问题，或者在初核和立案审查其问题（ ）交代组织未掌握的问题。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "前", "略", true, 0L));
        add(new MQuestion(340L, "党纪处分决定作出后，应当在（ ）向受处分党员所在党的基层组织中的全体党员及其本人宣布，是领导班子成员的还应当向所在党组织领导班子宣布，并按照干部管理权限和组织关系将处分决定材料归入受处分者档案。  ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "一个月内", "略", true, 0L));
        add(new MQuestion(341L, "《中国共产党巡视工作条例》于（）起施行。", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "2015年8月3日", "略", true, 0L));
        add(new MQuestion(342L, "根据《中国共产党巡视工作条例》，（）有义务向巡视组如实反映情况。", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "党员", "略", true, 0L));
        add(new MQuestion(343L, "根据《中国共产党巡视工作条例》，巡视工作坚持中央统一领导、分级负责；坚持实事求是、依法依规；坚持（）的原则。 ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "群众路线、发扬民主", "略", true, 0L));
        add(new MQuestion(344L, "根据《中国共产党巡视工作条例》，巡视组应当严格执行请示报告制度，对巡视工作中的（）要及时向巡视工作领导小组请示报告。", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "重要情况和重大问题", "略", true, 0L));
        add(new MQuestion(345L, "对执行民主集中制、干部选拔任用等方面存在的问题，移交（）。", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "有关组织部门", "略", true, 0L));
        add(new MQuestion(346L, "《中国共产党巡视工作条例》是落实党的十八大和十八届三中、四中全会精神，加强党内法规制度建设的具体成果，是全面从严治党的()利器。 ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "制度", "略", true, 0L));
        add(new MQuestion(347L, "巡视是( )的“利剑”，《中国共产党巡视工作条例》是发挥这一“利剑”作用的重要制度保障。 ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "党内监督", "略", true, 0L));
        add(new MQuestion(348L, "《中国共产党巡视工作条例》改进了巡视工作领导体制，明确要求“中央巡视工作领导小组应当加强对省、自治区、直辖市巡视工作的（）”。 ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "领导", "略", true, 0L));
        add(new MQuestion(349L, "《中国共产党巡视工作条例》规定，违反政治纪律和政治（），存在违背党的路线方针政策的言行，有令不行、有禁不止，阳奉阴违，拉帮结派等问题，是巡视组要着力发现的问题之一。 ", QuestionType.SingleChoice, QuestionClassification.Jilvxing, "规矩", "略", true, 0L));
        add(new MQuestion(350L, "有下列行为之一，对直接责任者和领导责任者，情节较重的，给予警告或者严重警告处分；情节严重的，给予撤销党内职务或者留党察看处分。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "对待群众态度恶劣、简单粗暴，造成不良影响的, 对涉及群众生产、生活等切身利益的问题依照政策或者有关规定能解决而不及时解决，庸懒无为、效率低下，造成不良影响的, 对符合政策的群众诉求消极应付、推诿扯皮，损害党群、干群关系的, 弄虚作假，欺上瞒下，损害群众利益的,有其他不作为、乱作为等损害群众利益行为的", "略", true, 0L));
        add(new MQuestion(351L, "有下列行为之一的，造成严重不良影响，对直接责任者和领导责任者，情节较轻的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "单纯以会议贯彻会议、以文件落实文件，在实际工作中不见诸行动的, 工作中有其他形式主义、官僚主义行为的, 热衷于搞舆论造势、浮在表面的, 贯彻党中央决策部署只表态不落实的", "略", true, 0L));
        add(new MQuestion(352L, "泄露、扩散或者打探、窃取党组织关于（ ）等尚未公开事项或者其他应当保密的内容的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "巡视巡察, 干部选拔任用, 纪律审查", "略", true, 0L));
        add(new MQuestion(353L, "有下列哪些行为，对直接责任者和领导责任者，情节严重的，给予开除党籍处分。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "以考察、学习、培训、研讨、招商、参展等名义变相用公款出国（境）旅游的, 用公款旅游、借公务差旅之机旅游, 违反有关规定滥发津贴、补贴、奖金, 违反有关规定组织、参加用公款支付的宴请、高消费娱乐、健身活动", "略", true, 0L));
        add(new MQuestion(354L, "下列哪些行为属于违反群众纪律的行为。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "克扣群众财物，或者违反有关规定拖欠群众钱款的, 在办理涉及群众事务时刁难群众、吃拿卡要的；在社会保障、政策扶持、扶贫脱贫、救灾救济款物分配等事项中优亲厚友、明显有失公平的, 超标准、超范围向群众筹资筹劳、摊派费用，加重群众负担的, 违反有关规定扣留、收缴群众款物或者处罚群众的", "略", true, 0L));
        add(new MQuestion(355L, "党的纪律处分工作应当坚持以下哪些原则。", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "党纪面前一律平等。, 坚持党要管党、全面从严治党。, 实事求是。, 民主集中制。", "略", true, 0L));
        add(new MQuestion(356L, "运用监督执纪“四种形态”，（）。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "严重违纪涉嫌违法立案审查的成为极少数。, 党纪轻处分、组织调整成为违纪处理的大多数, 党纪重处分、重大职务调整的成为少数, 经常开展批评和自我批评、约谈函询，让“红红脸、出出汗”成为常态", "略", true, 0L));
        add(new MQuestion(357L, "《中国共产党纪律处分条例》中规定的对党员的纪律处分种类有（）。", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "严重警告, 撤销党内职务, 留党察看, 警告", "略", true, 0L));
        add(new MQuestion(358L, "对于违犯党的纪律的党组织，上级党组织应当责令其作出检查或者进行通报批评。对于严重违犯党的纪律、本身又不能纠正的党组织，上一级党的委员会在查明核实后，根据情节严重的程度，可以予以（）。 ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "改组, 解散", "略", true, 0L));
        add(new MQuestion(359L, "《中国共产党纪律处分条例》对违纪行为有关责任人员区分为（）。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "主要领导责任者, 直接责任者, 重要领导责任者", "略", true, 0L));
        add(new MQuestion(360L, "《中国共产党纪律处分条例》所称领导责任者，包括（）。", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "主要领导责任者, 重要领导责任者", "略", true, 0L));
        add(new MQuestion(361L, "有下列情形之一的，可以从轻或者减轻处分。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "主动交代本人应当受到党纪处分的问题的, 主动挽回损失、消除不良影响或者有效阻止危害结果发生的, 在组织核实、立案审查过程中，能够配合核实审查工作，如实说明本人违纪违法事实的, 检举同案人或者其他人应当受到党纪处分或者法律追究的问题，经查证属实的", "略", true, 0L));
        add(new MQuestion(362L, "党员受留党察看处分期间，没有（）。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "表决权, 被选举权, 选举权", "略", true, 0L));
        add(new MQuestion(363L, "对于党员违犯党纪应当给予警告或者严重警告处分，但是具有《中国共产党纪律处分条例》规定的从轻或者减轻处分情形之一的，可以给予（ ），免予党纪处分。对违纪党员免予处分，应当作出书面结论。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "批评教育, 组织处理, 诫勉, 责令检查", "略", true, 0L));
        add(new MQuestion(364L, "有下列情形之一的，应当从重或者加重处分。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "强迫、唆使他人违纪的, 拒不上交或者退赔违纪所得的, 违纪受到党纪处分后，又被发现其受处分前的违纪行为应当受到党纪处分的, 违纪受处分后又因故意违纪应当受到党纪处分的", "略", true, 0L));
        add(new MQuestion(365L, "对抗组织审查，有下列行为之一的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "串供或者伪造、销毁、转移、隐匿证据的, 包庇同案人员的, 向组织提供虚假情况，掩盖事实的, 阻止他人揭发检举、提供证据材料的", "略", true, 0L));
        add(new MQuestion(366L, "有下列行为之一，情节较重的，给予警告或者严重警告处分。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "不如实填报个人档案资料的, 不按要求报告或者不如实报告个人去向的, 在组织进行谈话、函询时，不如实向组织说明问题, 违反个人有关事项报告规定，隐瞒不报的", "略", true, 0L));
        add(new MQuestion(367L, "有下列行为之一的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "压制党员申诉，造成不良后果的，或者不按照有关规定处理党员申诉的, 对党员的申辩、辩护、作证等进行压制，造成不良后果的, 对批评、检举、控告进行阻挠、压制，或者将批评、检举、控告材料私自扣压、销毁，或者故意将其泄露给他人的, 有其他侵犯党员权利行为，造成不良后果的", "略", true, 0L));
        add(new MQuestion(368L, "违反有关规定从事营利活动，有下列行为之一，情节较轻的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。  ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "买卖股票或者进行其他证券投资的, 从事有偿中介活动的, 拥有非上市公司（企业）的股份或者证券的, 经商办企业的", "略", true, 0L));
        add(new MQuestion(369L, "有下列行为之一，对直接责任者和领导责任者，情节较轻的，给予警告或者严重警告处分；情节较重的，给予撤销党内职务或者留党察看处分；情节严重的，给予开除党籍处分。   ", QuestionType.MultipleChoice, QuestionClassification.Jilvxing, "克扣群众财物，或者违反有关规定拖欠群众钱款的, 在管理、服务活动中违反有关规定收取费用的,在办理涉及群众事务时刁难群众、吃拿卡要的, 超标准、超范围向群众筹资筹劳、摊派费用，加重群众负担的, 违反有关规定扣留、收缴群众款物或者处罚群众的", "略", true, 0L));
        add(new MQuestion(370L, "《中国共产党廉洁自律准则》是专门针对领导干部廉洁从政而制定的法规。（  ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党廉洁自律准则》是一部面向全体党员的规范全党廉洁自律工作的重要法规。   ", true, 0L));
        add(new MQuestion(371L, "《中国共产党廉洁自律准则》是一部面向全体党员的规范全党廉洁自律工作的重要基础性法 规。（  ）     ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》是一部面向全体党员的规范全党廉洁自律工作的重要基础性法规。  ", true, 0L));
        add(new MQuestion(372L, "《中国共产党廉洁自律准则》自2016年1月1日起施行。（  ）    ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》自2016年1月1日起施行。  ", true, 0L));
        add(new MQuestion(373L, "《中国共产党廉洁自律准则》是由中央政治局审议通过的。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》是由中央政治局审议通过的。  ", true, 0L));
        add(new MQuestion(374L, "《中国共产党廉洁自律准则》第一条是：坚持崇廉拒腐，清白做人，干净做事。（  ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党廉洁自律准则》第一条是：坚持公私分明，先公后私，克己奉公。 ", true, 0L));
        add(new MQuestion(375L, "《中国共产党廉洁自律准则》第二条是：坚持崇廉拒腐，清白做人，干净做事。（  ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》第二条是：坚持崇廉拒腐，清白做人，干净做事。  ", true, 0L));
        add(new MQuestion(376L, "《中国共产党廉洁自律准则》第三条是：坚持尚俭戒奢，艰苦朴素，勤俭节约。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》第三条是：坚持尚俭戒奢，艰苦朴素，勤俭节约。   ", true, 0L));
        add(new MQuestion(377L, "《中国共产党廉洁自律准则》第四条是：廉洁从政，自觉保持人民公仆本色。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党廉洁自律准则》第四条是：坚持吃苦在前，享受在后，甘于奉献。   ", true, 0L));
        add(new MQuestion(378L, "《中国共产党廉洁自律准则》第五条是：坚持尚俭戒奢，艰苦朴素，勤俭节约。（  ）    ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党廉洁自律准则》第五条是：廉洁从政，自觉保持人民公仆本色。  ", true, 0L));
        add(new MQuestion(379L, "《中国共产党廉洁自律准则》第六条是：廉洁用权，自觉维护人民根本利益。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》第六条是：廉洁用权，自觉维护人民根本利益。 ", true, 0L));
        add(new MQuestion(380L, "《中国共产党廉洁自律准则》第七条是： 廉洁修身，自觉提升思想道德境界。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党廉洁自律准则》第七条是： 廉洁修身，自觉提升思想道德境界。   ", true, 0L));
        add(new MQuestion(381L, "《中国共产党廉洁自律准则》第八条是： 廉洁修身，自觉提升思想道德境界。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", " 《中国共产党廉洁自律准则》第八条是：廉洁齐家，自觉带头树立良好家风。  ", true, 0L));
        add(new MQuestion(382L, "《中国共产党纪律处分条例》以马克思列宁主义、毛泽东思想、邓小平理论、“三个代表”重要思想、科学发展观为指导，落实全面从严治党战略部署。（  ）      ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党纪律处分条例》第二条: 以马克思列宁主义、毛泽东思想、邓小平理论、“三个代表”重要思想、科学发展观为指导，深入贯彻习近平总书记系列重要讲话精神，落实全面从严治党战略部署。    ", true, 0L));
        add(new MQuestion(383L, "民主集中制是党的纪律处分工作应当坚持原则之一。（  ）   ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第四条:党的纪律处分工作应当坚持以下原则：（一）党要管党、从严治党。加强对党的各级组织和全体党员的教育、管理和监督，把纪律挺在前面，注重抓早抓小。（二）党纪面前一律平等。对违犯党纪的党组织和党员必须严肃、公正执行纪律，党内不允许有任何不受纪律约束的党组织和党员。（三）实事求是。对党组织和党员违犯党纪的行为，应当以事实为依据，以党章、其他党内法规和国家法律法规为准绳，准确认定违纪性质，区别不同情况，恰当予以处理。（四）民主集中制。实施党纪处分，应当按照规定程序经党组织集体讨论决定，不允许任何个人或者少数人擅自决定和批准。上级党组织对违犯党纪的党组织和党员作出的处理决定，下级党组织必须执行。（五）惩前毖后、治病救人。处理违犯党纪的党组织和党员，应当实行惩戒与教育相结合，做到宽严相济。   ", true, 0L));
        add(new MQuestion(384L, "党员受到开除党籍处分，三年内不得重新入党。（    ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党纪律处分条例》第十二条：党员受到开除党籍处分，五年内不得重新入党。", true, 0L));
        add(new MQuestion(385L, "党员受到留党察看处分，其党内职务保留一年。（    ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党纪律处分条例》第十一条：党员受到留党察看处分，其党内职务自然撤销。    ", true, 0L));
        add(new MQuestion(386L, "留党察看期限最长不得超过二年。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第十一条：留党察看期限最长不得超过二年。", true, 0L));
        add(new MQuestion(387L, "对于严重违犯党纪、本身又不能纠正的党组织领导机构，应当予以改组。（   ）    ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第十四条：对于严重违犯党纪、本身又不能纠正的党组织领导机构，应当予以改组。   ", true, 0L));
        add(new MQuestion(388L, "党的各级代表大会的代表受到留党察看以上（含留党察看）处分的，党组织应当终止其代表资格。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第十三条：党的各级代表大会的代表受到留党察看以上(含留党察看)处分的，党组织应当终止其代表资格。   ", true, 0L));
        add(new MQuestion(389L, "对于全体或者多数党员严重违犯党纪的党组织，应当予以改组。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党纪律处分条例》第十五条：对于全体或者多数党员严重违犯党纪的党组织，应当予以解散。 ", true, 0L));
        add(new MQuestion(390L, "对于受到解散处理的党组织中的党员，应当逐个审查。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第十五条：对于受到解散处理的党组织中的党员，应当逐个审查。    ", true, 0L));
        add(new MQuestion(391L, "根据案例的特殊情况，由中央纪委决定或者经省（部）级纪委（不含副省级市纪委）决定并呈报中央纪委批准，对违纪党员也可以在本条例规定的处分幅度以外减轻处分。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第十七条：根据案件的特殊情况，由中央纪委决定或者经省(部)级纪委(不含副省级市纪委)决定并呈报中央纪委批准，对违纪党员也可以在本条例规定的处分幅度以外减轻处分。   ", true, 0L));
        add(new MQuestion(392L, "在纪律集中整饬过程中，不收敛、不收手的，应当从重或者加重处分。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第十九条：有下列情形之一的，应当从重或者加重处分: (一)在纪律集中整饬过程中，不收敛、不收手的；(二)强迫、唆使他人违纪的；(三)本条例另有规定的。  ", true, 0L));
        add(new MQuestion(393L, "故意违纪受处分后又因故意违纪应当受到党纪处分的，应当从重处分。（   ）    ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第二十条：故意违纪受处分后又因故意违纪应当受到党纪处分的，应当从重处分。    ", true, 0L));
        add(new MQuestion(394L, "党员违纪受到党纪处分后，又被发现其受处分前的违纪行为应当受到党纪处分的，应当从重处分。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第二十条：党员违纪受到党纪处分后，又被发现其受处分前的违纪行为应当受到党纪处分的，应当从重处分。", true, 0L));
        add(new MQuestion(395L, "从轻处分，是指在《中国共产党纪律处分条例》规定的违纪行为应当受到的处分幅度以内，给予较轻的处分。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第二十一条：从轻处分，是指在本条例规定的违纪行为应当受到的处分幅度以内，给予较轻的处分。    ", true, 0L));
        add(new MQuestion(396L, "减轻处分，是指在《中国共产党纪律处分条例》规定的违纪行为应当受到的处分幅度以外，减轻一档给予处分。（   ）      ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第二十二条减轻处分，是指在本条例规定的违纪行为应当受到的处分幅度以外，减轻一档给予处分。 加重处分，是指在本条例规定的违纪行为应当受到的处分幅度以外，加重一档给予处分。    ", true, 0L));
        add(new MQuestion(397L, "加重处分，是指在《中国共产党纪律处分条例》规定的违纪行为应当受到的处分幅度以外，加重二档给予处分。（   ）     ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "F", "《中国共产党纪律处分条例》第二十二条减轻处分，是指在本条例规定的违纪行为应当受到的处分幅度以外，减轻一档给予处分。 加重处分，是指在本条例规定的违纪行为应当受到的处分幅度以外，加重一档给予处分。   ", true, 0L));
        add(new MQuestion(398L, "一人有两种以上(含两种)应当受到党纪处分的违纪行为，其中一种违纪行为应当受到开除党籍处分的，应当给予开除党籍处分。（   ） ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第二十三条：一人有本条例规定的两种以上(含两种)应当受到党纪处分的违纪行为，应当合并处理，按其数种违纪行为中应当受到的最高处分加重一档给予处分；其中一种违纪行为应当受到开除党籍处分的，应当给予开除党籍处分。   ", true, 0L));
        add(new MQuestion(399L, "二人以上(含二人)共同故意违纪的，对为首者，从重处分。（   ）  ", QuestionType.TrueOrFalse, QuestionClassification.Jilvxing, "T", "《中国共产党纪律处分条例》第二十五条：二人以上(含二人)共同故意违纪的，对为首者，从重处分。 ", true, 0L));
        add(new MQuestion(400L, "《中国共产党党员领导干部廉洁从政若干准则》（以下简称《廉政准则》），是根据___________，结合党员领导干部廉洁自律工作实际修订的。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "《中国共产党章程》 ", "《中国共产党党员领导干部廉洁从政若干准则》（以下简称《廉政准则》），是根据《中国共产党章程》，结合党员领导干部廉洁自律工作实际修订的。  ", true, 0L));
        add(new MQuestion(401L, "《廉政准则》强调，党员领导干部廉洁从政是不断加强党的__________建设和先进性建设的重要内容，是正确行使权力、履行职责的重要基础。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "执政能力  ", "《廉政准则》强调，党员领导干部廉洁从政是不断加强党的执政能力建设和先进性建设的重要内容，是正确行使权力、履行职责的重要基础。  ", true, 0L));
        add(new MQuestion(402L, "党员领导干部必须模范遵守_________，清正廉洁，忠于职守，正确行使权力，始终保持职务行为的廉洁性  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "党纪国法 ", "党员领导干部必须模范遵守党纪国法，清正廉洁，忠于职守，正确行使权力，始终保持职务行为的廉洁性。  ", true, 0L));
        add(new MQuestion(403L, "促进党员领导干部廉洁从政，必须坚持________、综合治理、惩防并举、注重预防的方针。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "标本兼治 ", "促进党员领导干部廉洁从政，必须坚持标本兼治、综合治理、惩防并举、注重预防的方针。", true, 0L));
        add(new MQuestion(404L, "坚决惩治和有效预防腐败，是党必须始终抓好的________任务。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "重大政治 ", "坚决惩治和有效预防腐败，是党必须始终抓好的重大政治任务。", true, 0L));
        add(new MQuestion(405L, "《廉政准则》规定，党的纪律检查机关协助同级党委（党组）抓好本准则的落实，并负责对实施情况进行__________。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "监督检查 ", "《廉政准则》规定，党的纪律检查机关协助同级党委（党组）抓好本准则的落实，并负责对实施情况进行监督检查。", true, 0L));
        add(new MQuestion(406L, "《廉政准则》第一章是___________。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "廉洁从政行为规范 ", "《廉政准则》第一章是廉洁从政行为规范。", true, 0L));
        add(new MQuestion(407L, "禁止利用职权和职务上的影响为亲属及身边工作人员谋取利益。不准利用职务之便，为他人谋取利益，其父母、配偶、子女及其配偶以及其他_________收受对方财物。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "特定关系人  ", "禁止利用职权和职务上的影响为亲属及身边工作人员谋取利益，不准利用职务之便，为他人谋取利益，其父母、配偶、子女及其配偶以及其他特定关系人          收受对方财物。  ", true, 0L));
        add(new MQuestion(408L, "禁止脱离实际，弄虚作假，损害群众利益和党群干群关系。不准搞劳民伤财的“形象工程 ”和沽名钓誉的“________”。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "政绩工程  ", "禁止脱离实际，弄虚作假，损害群众利益和党群干群关系。不准搞劳民伤财的“形象工程”和沽名钓誉的“政绩工程”。", true, 0L));
        add(new MQuestion(409L, "《廉政准则》规定，党员领导干部不准__________建设工程项目承发包、土地使用权出让、政府采购、房地产开发与经营、矿产资源开发利用、中介机构服务等市场经济活动。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "干预和播手  ", "《廉政准则》规定，党员领导干部不准干预和播手建设工程项目承发包、土地使用权出让、政府采购、房地产开发与经营、矿产资源开发利用、中介机构服务等市场经济活动。  ", true, 0L));
        add(new MQuestion(410L, "《廉政准则》规定，不准用公款参与高消费娱乐、健身活动和获取各种形式的 俱乐部________。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "会员资格 ", "《廉政准则》规定，不准用公款参与高消费娱乐、健身活动和获取各种形式的 俱乐部会员资格。 ", true, 0L));
        add(new MQuestion(411L, "领导干部不准干预和插手农村___________、资产和资源的使用、分配、承包、租赁等事项。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "集体资金  ", "领导干部不准干预和插手农村集体资金、资产和资源的使用、分配、承包、租赁等事项。  ", true, 0L));
        add(new MQuestion(412L, "中共中央关于印发《廉政准则》的通知要求，要严格对党员领导干部的管理和监督，切实到预防为先、__________。", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "关口前移 ", "中共中央关于印发《廉政准则》的通知要求，要严格对党员领导干部的管理和监督，切实到预防为先、关口前移。", true, 0L));
        add(new MQuestion(413L, "各级党委(党组)要加强对党员领导干部廉洁从政方面的教育，将《廉洁政准则》 列为党员领导干部_________的重要内容。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "教育和培训   ", "各级党委(党组)要加强对党员领导干部廉洁从政方面的教育，将《廉洁政准则》 列为党员领导干部教育和培训的重要内容。 ", true, 0L));
        add(new MQuestion(414L, "贯彻实施《廉政准则》，要坚持_________与党外监督相结合，发挥民主党派、人民团体、人民群众和新闻舆论的监督作用。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "党内监督 ", "贯彻实施《廉政准则》，要坚持党内监督与党外监督相结合，发挥民主党派、人民团体、人民群众和新闻舆论的监督作用。  ", true, 0L));
        add(new MQuestion(415L, "党员领导干部参加_________和述职述廉，要对照《廉政准则》进行检查，认真开展批评和自我批评。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "民主生活会   ", "党员领导干部参加民主生活会和述职述廉，要对照《廉政准则》进行检查，认真开展批评和自我批评。 ", true, 0L));
        add(new MQuestion(416L, "《廉政准则》规定，党员领导干部组织实施和执行本准则的情况，应列入   党员廉政建设和________的重要内容，考核结果作为对其任免、奖惩的重要依据。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "干部考核   ", "《廉政准则》规定，党员领导干部组织实施和执行本准则的情况，应列入党员廉政建设和干部考核的重要内容，考核结果作为对其任免、奖惩的重要依据。", true, 0L));
        add(new MQuestion(417L, "《廉政准则》规定，党员领导干部应当向党组织如实报告_________，自觉接受监督。   ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "个人有关事项 ", "《廉政准则》规定，党员领导干部应当向党组织如实报告个人有关事项，自觉接受监督。   ", true, 0L));
        add(new MQuestion(418L, "选拔任用干部，不准私自泄露民主推荐、_________、考察、酝酿、讨论决定干部等有关情况。  ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "民主测评 ", "选拔任用干部，不准私自泄露民主推荐、民主测评、考察、酝酿、讨论决定干部等有关情况。  ", true, 0L));
        add(new MQuestion(419L, "禁止脱离实际，弄虚作假，损害群众利益和党群干群关系。不准在社会保障、 政策扶持、________等事项中优亲厚友、显失公平。 ", QuestionType.BlanksFilling, QuestionClassification.Jilvxing, "救灾救济", "禁止脱离实际，弄虚作假，损害群众利益和党群干群关系。不准在社会保障、政策扶持、救灾救济等事项中优亲厚友、显失公平。 ", true, 0L));
        add(new MQuestion(420L, "中国共产党第十九次全国代表大会，是在全面建成小康社会决胜阶段、中国特色社会主义进入_____的关键时期召开的一次十分重要的大会。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "新时代", "略", true, 0L));
        add(new MQuestion(421L, "十九大的主题是：不忘初心，____，高举中国特色社会主义伟大旗帜，决胜全面建成小康社会，夺取新时代中国特色社会主义伟大胜利，为实现中华民族伟大复兴的中国梦不懈奋斗。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "牢记使命", "略", true, 0L));
        add(new MQuestion(422L, "中国共产党人的初心和使命，就是为中国人民____ ，为中华民族____。这个初心和使命是激励中国共产党人不断前进的根本动力。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "谋幸福，谋复兴", "略", true, 0L));
        add(new MQuestion(423L, "五年来，我们统筹推进“____”总体布局、协调推进“____”战略布局，“十二五”规划胜利完成，“十三五”规划顺利实施，党和国家事业全面开创新局面。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "五位一体", "略", true, 0L));
        add(new MQuestion(424L, "过去五年，经济保持中高速增长，在世界主要国家中名列前茅，国内生产总值从五十四万亿元增长到____万亿元，稳居世界第二，对世界经济增长贡献率超过百分之三十。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "八十", "略", true, 0L));
        add(new MQuestion(425L, "脱贫攻坚战取得决定性进展，____贫困人口稳定脱贫，贫困发生率从百分之十点二下降到百分之四以下。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "六千多万", "略", true, 0L));
        add(new MQuestion(426L, "实施共建“一带一路”倡议，发起创办亚洲基础设施投资银行，设立丝路基金，举办首届“一带一路”国际合作高峰论坛、亚太经合组织领导人非正式会议、二十国集团领导人____峰会、金砖国家领导人____会晤、亚信峰会。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "南京", "略", true, 0L));
        add(new MQuestion(427L, "坚持反腐败无禁区、全覆盖、零容忍，坚定不移“打虎”、“拍蝇”、“猎狐”，____的目标初步实现，____的笼子越扎越牢，____的堤坝正在构筑，反腐败斗争压倒性态势已经形成并巩固发展。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "不敢腐", "略", true, 0L));
        add(new MQuestion(428L, "经过长期努力，中国特色社会主义进入了新时代，这是我国发展新的____。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "历史方位", "略", true, 0L));
        add(new MQuestion(429L, "中国特色社会主义进入新时代，我国社会主要矛盾已经转化为人民日益增长的____需要和____的发展之间的矛盾。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "不平衡不充分", "略", true, 0L));
        add(new MQuestion(430L, "必须认识到，我国社会主要矛盾的变化，没有改变我们对我国社会主义所处历史阶段的判断，我国仍处于并将长期处于____的基本国情没有变，我国是世界最大发展中国家的国际地位没有变。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "社会主义初级阶段", "略", true, 0L));
        add(new MQuestion(431L, "____是实现社会主义现代化、创造人民美好生活的必由之路。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "中国特色社会主义道路", "略", true, 0L));
        add(new MQuestion(432L, "_____是指导党和人民实现中华民族伟大复兴的正确理论。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "中国特色社会主义理论体系", "略", true, 0L));
        add(new MQuestion(433L, "_____是当代中国发展进步的根本制度保障。   ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "中国特色社会主义制度", "略", true, 0L));
        add(new MQuestion(434L, "_____中国特色社会主义文化是激励全党全国各族人民奋勇前进的强大精神力量。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "中国特色社会主义文化", "略", true, 0L));
        add(new MQuestion(435L, "新时代中国特色社会主义思想，明确坚持和发展中国特色社会主义，总任务是实现社会主义现代化和中华民族伟大复兴，在全面建成小康社会的基础上，分____在本世纪中叶建成富强民主文明和谐美丽的社会主义现代化强国。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "两步走", "略", true, 0L));
        add(new MQuestion(436L, "新时代中国特色社会主义思想，明确中国特色社会主义最本质的特征是____。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "中国共产党领导", "略", true, 0L));
        add(new MQuestion(437L, "发展是解决我国一切问题的基础和关键，发展必须是科学发展，必须坚定不移贯彻____的发展理念。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "创新、协调、绿色、开放、共享", "略", true, 0L));
        add(new MQuestion(438L, "____是中国特色社会主义的本质要求和重要保障。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "全面依法治国", "略", true, 0L));
        add(new MQuestion(439L, "____是一个国家、一个民族发展中更基本、更深沉、更持久的力量。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "文化自信", "略", true, 0L));
        add(new MQuestion(440L, "必须统筹国内国际两个大局，始终不渝走和平发展道路、奉行____的开放战略。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "互利共赢", "略", true, 0L));
        add(new MQuestion(441L, "从现在到二〇二〇年，是全面建成小康社会______。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "决胜期", "略", true, 0L));
        add(new MQuestion(442L, "从____到____，是“两个一百年”奋斗目标的历史交汇期。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "二〇三五年", "略", true, 0L));
        add(new MQuestion(443L, "综合分析国际国内形势和我国发展条件，从二〇二〇年到本世纪中叶可以分两个阶段来安排。第一个阶段，从______到______，在全面建成小康社会的基础上，再奋斗十五年，基本实现社会主义现代化。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "二〇二〇年", "略", true, 0L));
        add(new MQuestion(444L, "综合分析国际国内形势和我国发展条件，从二〇二〇年到本世纪中叶可以分两个阶段来安排。第二个阶段，从_____到_____，在基本实现现代化的基础上，再奋斗十五年，把我国建成富强民主文明和谐美丽的社会主义现代化强国。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "二〇五〇年", "略", true, 0L));
        add(new MQuestion(445L, "从全面建成小康社会到基本实现现代化，再到全面建成____，是新时代中国特色社会主义发展的战略安排。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "社会主义现代化强国", "略", true, 0L));
        add(new MQuestion(446L, "实现“两个一百年”奋斗目标、实现中华民族伟大复兴的中国梦，不断提高人民生活水平，必须坚定不移把_____作为党执政兴国的第一要务。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "发展", "略", true, 0L));
        add(new MQuestion(447L, "我国经济已由______阶段转向______阶段，正处在转变发展方式、优化经济结构、转换增长动力的攻关期，建设现代化经济体系是跨越关口的迫切要求和我国发展的战略目标。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "高速发展", "略", true, 0L));
        add(new MQuestion(448L, "贯彻新发展理念，建设现代化经济体系，必须坚持质量第一、效益优先，以_______为主线。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "供给侧结构性改革", "略", true, 0L));
        add(new MQuestion(449L, "建设现代化经济体系，必须把发展经济的着力点放在______上，把提高供给体系质量作为主攻方向，显著增强我国经济质量优势。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "实体经济", "略", true, 0L));
        add(new MQuestion(450L, "______是引领发展的第一动力，是建设现代化经济体系的战略支撑。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "创新", "略", true, 0L));
        add(new MQuestion(451L, "保持土地承包关系稳定并长久不变，第二轮土地承包到期后再延长_____年。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "三十", "略", true, 0L));
        add(new MQuestion(452L, "确保到______我国现行标准下农村贫困人口实现脱贫，贫困县全部摘帽，解决区域性整体贫困，做到脱真贫、真脱贫。", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "二〇二〇年", "略", true, 0L));
        add(new MQuestion(453L, "加快完善社会主义市场经济体制。经济体制改革必须以________和________为重点，实现产权有效激励、要素自由流动、价格反应灵活、竞争公平有序、企业优胜劣汰。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "完善产权制度", "略", true, 0L));
        add(new MQuestion(454L, "推动形成全面开放新格局。要以_____建设为重点，坚持引进来和走出去并重，遵循共商共建共享原则，加强创新能力开放合作，形成陆海内外联动、东西双向互济的开放格局。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "“一带一路”", "略", true, 0L));
        add(new MQuestion(455L, "赋予自由贸易试验区更大改革自主权，探索建设______。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "自由贸易港", "略", true, 0L));
        add(new MQuestion(456L, "坚持党的领导、人民当家作主、依法治国有机统一。_______是社会主义民主政治的本质特征。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "人民当家作主", "略", true, 0L));
        add(new MQuestion(457L, "加强人民当家作主制度保障。______是坚持党的领导、人民当家作主、依法治国有机统一的根本政治制度安排。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "人民代表大会制度", "略", true, 0L));
        add(new MQuestion(458L, "发挥社会主义协商民主重要作用。______是具有中国特色的制度安排，是社会主义协商民主的重要渠道和专门协商机构。 ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "人民政协", "略", true, 0L));
        add(new MQuestion(459L, "深化依法治国实践。成立中央全面______领导小组，加强对法治中国建设的统一领导。  ", QuestionType.SingleChoice, QuestionClassification.Sixiangxianjinxing, "依法治国", "略", true, 0L));
        add(new MQuestion(460L, "健全完善（）各环节标准体系，推进“三通一标”向各电压等级延伸覆盖。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "物资采购, 规划可研, 设计建设, 运维检修", "略", true, 0L));
        add(new MQuestion(461L, "要以（）等为重点，发展混合所有制，放大国有资本功能。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "产业和金融单位, 增量配电投资业务放开, 抽水蓄能电站建设", "略", true, 0L));
        add(new MQuestion(462L, "习近平总书记对国有企业领导人员提出的（）20字要求，是公司各级领导干部的努力方向，要主动践行，抓好班子、带好队伍、管好自己，做“忠诚、干净、担当”的好干部。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "兴企有为, 勇于创新, 对党忠诚, 治企有方", "略", true, 0L));
        add(new MQuestion(463L, "落实公司《关于强化本质安全的决定》，把（）作为硬约束，明确具体任务，强化监督考核，确保各项措施落实到位。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "严控风险, 执行制度, 治理隐患, 统一标准", "略", true, 0L));
        add(new MQuestion(464L, "强化协同监督，完善（）等专业一体化协同监督机制。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "审计, 纪检监察, 财务", "略", true, 0L));
        add(new MQuestion(465L, "金融要强化资本运作，在（）方面取得实质突破。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "上市, 发展互联网金融, 引进战略投资者", "略", true, 0L));
        add(new MQuestion(466L, "加强物资全流程管控，切实解决（）等不规范问题。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "应招未招, 未核先招, 账实不符", "略", true, 0L));
        add(new MQuestion(467L, "加强资产运行状态全过程监测，开展（）情况分析，优化资产运营策略，建立退出退役设备跨区域调配机制。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "使用寿命, 运维成本, 采购成本", "略", true, 0L));
        add(new MQuestion(468L, "提高快速响应客户需求能力，研究整合（）等力量，试点建立集营配调资源调动和业务运转于一体的供电服务指挥平台。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "95598工单接派, 设备抢修, 配电网运行协调", "略", true, 0L));
        add(new MQuestion(469L, "深化“互联网+营销服务”，按照（）的要求，整合“掌上电力”", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "“电, 功能融合, 宝”、95598网站及在线客服资源，提高移动服务便捷性、可靠性。", "略", true, 0L));
        add(new MQuestion(470L, "认真落实《中国制造2025》，聚焦高端装备和（）等战略性新兴产业，深化重组整合，优化业务布局，努力打造高品质电工装备知名品牌。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "低碳经济, 信息通信, 节能环保", "略", true, 0L));
        add(new MQuestion(471L, "公司深入研究改革重大问题，在（）等方面促进形成重要共识。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "《电力法》修订, 售电侧和增量配电投资业务放开, 电力市场交易机构组建, 输配电价改革", "略", true, 0L));
        add(new MQuestion(472L, "中央经济工作会议明确要坚持稳中求进工作总基调，适应把握引领经济发展新常态，以推进供给侧结构性改革为主线，全面做好（）各项工作。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "促改革, 惠民生, 稳增长, 调结构", "略", true, 0L));
        add(new MQuestion(473L, "2016年是很不平凡的一年，是辛勤耕耘、收获巨大的一年，我们在工作中的深切体会有（）。   ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "坚持以改革创新为强大动力, 坚持全心全意依靠职工办企业, 坚持发展战略目标不动摇, 坚持把党的领导作为根本保证", "略", true, 0L));
        add(new MQuestion(474L, "适应全面深化改革、参与市场竞争的新形势，必须进一步转变公司发展方式，突出效率和效益导向，把（）向纵深推进，全面提升现代化管理水平。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "精益化, 集团化, 集约化", "略", true, 0L));
        add(new MQuestion(475L, "认真贯彻国家（）等重大战略部署，优化“十三五”电网发展规划，制定了电网配套行动计划和实施方案。   ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "京津冀协同发展, 振兴东北老工业基地, 稳增长调结构惠民生", "略", true, 0L));
        add(new MQuestion(476L, "（）是电网发展的本质要求。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "优质, 安全, 高效", "略", true, 0L));
        add(new MQuestion(477L, "公司上下要进一步增强改革意识，顺应改革大势，积极（），推动改革措施尽快落地，有效释放改革红利。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "参与改革, 拥护改革, 支持改革", "略", true, 0L));
        add(new MQuestion(478L, "加快配电网建设改造，建设智能现代城市配电网，提高建设标准、设备质量和自动化水平，做到（），避免大拆大建。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "变电站土建一次完成, 导线截面一次选定, 廊道一次到位", "略", true, 0L));
        add(new MQuestion(479L, "全面推进十大科技创新工程,加强大容量直流换流变压器、换流阀等关键设备研发，推动（）等重大关键技术取得突破。  ", QuestionType.MultipleChoice, QuestionClassification.Sixiangxianjinxing, "大容量储能, 柔性直流输电, 海底电缆", "略", true, 0L));
        add(new MQuestion(480L, "新修订的党章规定，中国共产党以马克思列宁主义、毛泽东思想、邓小平理论、“三个代表”重要思想和科学发展观作为自己的行动指南。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "请参考习近平新时代中国特色社会主义思想  ", true, 0L));
        add(new MQuestion(481L, "巡视是党内监督的战备性制度安排，是“国之利器、党之利器”。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(482L, "党的全面领导必须体现在党的治国理政方方面面，体现在国家政权的机构、体制、制度等的设计、安排、运行之中。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(483L, "确立和维护无产阶级政党的领导核心始终是马克思主义建党学说的根本观点。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(484L, "为贯彻十八大精神，党中央召开六次全会，分别就政府机构改革和职能转变、全面深化改革、全面推进依法治国、制定“十三五”规划、全面从严治党等重大问题作出决定和部署。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应为七次 ", true, 0L));
        add(new MQuestion(485L, "党的组织建设是党的根本性建设，决定党的建设方向和效果。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应为党的政治建设  ", true, 0L));
        add(new MQuestion(486L, "党的十九大报告指出，我国经济保持中高速增长，在世界主要国家中名列前茅，国内生产总值从五十四万亿元增长到八十万亿元，稳居世界第二，对世界经济增长贡献率超过百分之四十。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "“百分之四十”应为“百分之三十”", true, 0L));
        add(new MQuestion(487L, "党的十九大报告指出，十八大以来的五年，改革全面发力、多点突破、纵深推进、着力增强改革系统性、整体性、协同性，压茬拓展改革广度和深度，推出一千五百多项改革举措。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(488L, "党的十九大报告指出，十八大以来，科学立法、严格执法、公正司法、全民守法深入推进，法治国家、法治政党、法治社会建设相互促进，中国特色社会主义法制体系日益完善，全社会法制观念明显增强。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "“法治政党”应为“法治政府” ", true, 0L));
        add(new MQuestion(489L, "改革开放的一项重大历史任务就是推动中国特色社会主义制度更加成熟、更加定型。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(490L, "党的十八大以来，我国经济实力、科技实力大幅跃升，跻身创新型国家前列。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应到2035年目标", true, 0L));
        add(new MQuestion(491L, "推进国家治理体系和治理能力现代化，可以在人权、选举制度、法治等重大问题上向西方制度模式看齐，但绝不能照搬。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "不能西方化、资本主义化 ", true, 0L));
        add(new MQuestion(492L, "做好意识形态工作，党委宣传部长是第一责任人。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "党委主要负责人", true, 0L));
        add(new MQuestion(493L, "党的十九大报告指出，脱贫攻坚战取得决定性进展，六千多万贫困人口稳定脱贫，贫困发生率从百分之九点二下降到百分之四以下。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应为十点二", true, 0L));
        add(new MQuestion(494L, "建设强大的现代化陆军、海军、空军、火箭军和战略支援部队，打造坚强高效的军种联合作战指挥机构。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "“军种”应为“战区” ", true, 0L));
        add(new MQuestion(495L, "习近平总书记强调，我们坚决维护国家主权和领土完整，绝不容忍国家分裂的历史悲剧重演。一切分裂祖国的活动都必将遭到全体中国人坚决反对。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想  ", true, 0L));
        add(new MQuestion(496L, "国防和军队改革取得历史性突破，形成军委管总、战区主战、军种主建新格局，人民军队组织架构和力量体系实现革命性重塑。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(497L, "以经济建设为中心是新时代坚持和发展中国特色社会主义根本立场。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应为以人民为中心 ", true, 0L));
        add(new MQuestion(498L, "当前和今后一个时期，我国经济发展面临的问题，供给和需求两侧都有，但矛盾的主要方面在需求侧。   ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "矛盾的主要方面在供给侧", true, 0L));
        add(new MQuestion(499L, "习近平总书指出，要提拔重用牢固树立“四个意识”和“四个自信”、坚决维护党中央权威、全面贯彻执行党的理论和路线方针政策、忠诚干净担当的干部。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想 ", true, 0L));
        add(new MQuestion(500L, "中国共产党始终把为人类作出新的更大的贡献作为自己的使命。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想 ", true, 0L));
        add(new MQuestion(501L, "中国坚定奉行独立自主的和平外交政策，尊重各国人民自主选择发展道路的全力，维护国际公平正义，反对把自己的意志强加于人，反对干涉别国内政，反对以强凌弱。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(502L, "我们党深刻认识到，实现中华民族伟大复兴，必须建立符合世界标准的先进社会制度。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应为必须建立符合我国实际的先进社会制度 ", true, 0L));
        add(new MQuestion(503L, "全党要充分认识这场伟大斗争的长期性、复杂性、艰巨性，发扬斗争精神，提高斗争本领，不断夺取伟大斗争新胜利。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想 ", true, 0L));
        add(new MQuestion(504L, "一个政党，一个政权，其前途命运取决于人心向背，人民群众反对什么、痛恨什么，我们就要坚决防范和纠正什么。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想  ", true, 0L));
        add(new MQuestion(505L, "从2020年到2035年，在全面建成小康社会的基础上，再奋斗十五年，实现社会主义现代化。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "应为基本实现社会主义现代化", true, 0L));
        add(new MQuestion(506L, "发展是解决我国一切问题的基础和关键，发展必须是科学发展，必须坚定不移贯彻创新、协调、绿色、开放、共享的发展理念。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想  ", true, 0L));
        add(new MQuestion(507L, "党的十九大报告指出，从现在到2035年，是全面建成小康社会决胜期。 ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "“2035”应为“2020”  ", true, 0L));
        add(new MQuestion(508L, "党的十九大报告指出，要建设知识型、技能型、服务型劳动者大军，弘扬劳模精神和工匠精神，营造劳动光荣的社会风尚和精益求精的敬业风气。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "F", "“服务型”应为“创新型”  ", true, 0L));
        add(new MQuestion(509L, "党的十九大报告指出，要倡导创新文化，强化知识产权创造、保护、运用。  ", QuestionType.TrueOrFalse, QuestionClassification.Sixiangxianjinxing, "T", "请参考习近平新时代中国特色社会主义思想", true, 0L));
        add(new MQuestion(510L, "十九大的主题是：不忘初心，_______，高举中国特色社会主义伟大旗帜，决胜全面建成小康，争取新时代中国特色社会主义伟大胜利，为实现中华民族伟大复兴的中国梦不懈奋斗。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "牢记使命  ", "略", true, 0L));
        add(new MQuestion(511L, "五年来,我们统筹推进“_______”总体布局、协调推进“四个全面”战略布局,“十二五”规划胜利完成,“十三五”规划顺利实施,党和国家事业全面开创新局面。 ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "五位一体  ", "略", true, 0L));
        add(new MQuestion(512L, "人类命运共同体指在追求本国利益时兼顾他国________，在谋求本国发展中促进各国共同发展。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "合理关切  ", "略", true, 0L));
        add(new MQuestion(513L, "“精准扶贫”的重要思想最早是在_______年11月，习近平到湖南湘西考察时首次作出了 “实事求是、因地制宜、分类指导、精准扶贫”的重要指示。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "2013  ", "略", true, 0L));
        add(new MQuestion(514L, "过去五年,经济保持中高速增长,在世界主要国家中名列前茅,国内生产总值从五十四万亿元增长到_______万亿元,稳居世界第二,对世界经济增长贡献率超过百分之三十。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "八十", "略", true, 0L));
        add(new MQuestion(515L, " 必须认识到,我国社会主要矛盾的变化,没有改变我们对我国社会主义所处历史阶段的判断,我国仍处于并将长期处于_______的基本国情没有变,我国是世界最大发展中国家的国际地位没有变。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "社会主义初级阶段 ", "略", true, 0L));
        add(new MQuestion(516L, "党的根本组织原则是_______。 ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "民主集中制。  ", "略", true, 0L));
        add(new MQuestion(517L, "“四个全面”战略布局是全面建成小康社会，全面深化改革，全面依法治国和________。   ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "全面从严治党  ", "略", true, 0L));
        add(new MQuestion(518L, "党在新时代的强军目标是建设一支听党指挥，能打胜仗，________的人民军队。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "作风优良  ", "略", true, 0L));
        add(new MQuestion(519L, "中国特色大国外交要推动构建新型国际关系，推动构建________。 ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "人类命运共同体 ", "略", true, 0L));
        add(new MQuestion(520L, "党的十九大的全称是________。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "中国共产党第十九次全国代表大会。  ", "略", true, 0L));
        add(new MQuestion(521L, "党的十九大通过的党章修正案把________确立为我们党的行动指南，实现了党的指导思想的又一次与时俱进。", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "习近平新时代中国特色社会主义思想 ", "略", true, 0L));
        add(new MQuestion(522L, "新时代我国社会主要矛盾是_________。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾 ", "略", true, 0L));
        add(new MQuestion(523L, " “两学一做”指的是学党章党规，学系列讲话，___________。", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "做合格党员", "略", true, 0L));
        add(new MQuestion(524L, "中共十九届三中全会的主题是___________。 ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "深化党和国家机构改革。 ", "略", true, 0L));
        add(new MQuestion(525L, "中国特色社会主义最本质的特征是_____________。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "中国共产党的领导。  ", "略", true, 0L));
        add(new MQuestion(526L, "党的领导主要表现在_________、思想领导、和组织领导方面。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "政治领导", "略", true, 0L));
        add(new MQuestion(527L, "四个自信指_______、理论自信、制度自信、文化自信。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "道路自信", "略", true, 0L));
        add(new MQuestion(528L, "五大发展理念指_________、协调发展、绿色发展、开放发展和共享发展。   ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "创新发展 ", "略", true, 0L));
        add(new MQuestion(529L, "实现社会主义现代化、创造人民美好生活的必由之路是___________。  ", QuestionType.BlanksFilling, QuestionClassification.Sixiangxianjinxing, "中国特色社会主义道路", "略", true, 0L));
    }};

    public static final Long currentMaxLength = (long)allQuestions.size();
}
